### ISSUE TITLE
symbol lists?

### ISSUE THREAD

**Issue by nicferrier** [magnars/dash.el#100]
This is often necessary but there's nothing in emacs for it:

```
(defun list-symbols (regex)
  (let ((lst))
    (mapatoms
     (lambda (a)
       (when (string-match-p regex (symbol-name a))
         (push a lst))))
    lst))
```

it's heavily related to dash core function, list processing, but it isn't exactly list processing per se. This is more of a very common generator function.

Is it worthwhile adding something like this?

**Comment by Fuco1** [comment]
This seems related to #134.

**Comment by basil-conto** [comment]
> This seems related to #134.

Which was closed, and there's been no further interest here either, so I'm closing this too.
