### ISSUE TITLE
Equivalent of `cl-some`

### ISSUE THREAD

**Issue by wasamasa** [magnars/dash.el#122]
`-any?` is a predicate returning a boolean. `-first` returns me the element, not the value of the "predicate" applied to it.  Is there anything better than `(car (-keep 'pred list))`?  If not, how would I go about implementing it?

**Comment by Fuco1** [comment]
`(pred (-first 'pred list))`

**Comment by wasamasa** [comment]
Hmm, feels a bit redundant though since I shouldn't have the need to apply `pred` a second time.

**Comment by magnars** [comment]
In clojure, the feature you're requesting would be `some`. Pull request welcome!

**Comment by wasamasa** [comment]
I consider just calling it `-any` since it's `any` in SRFI-1. `-some` would work as well and could be an alias.

**Comment by magnars** [comment]
The dash library so far has used Clojure Core as a naming guideline.

**Comment by wasamasa** [comment]
OK, I'll do it the other way around then and make `-any` the alias of `-some`.

In what section of the README would I put that function? Does it belong to predicates although it's not really one?

**Comment by magnars** [comment]
The README is auto-generated from the `dev/examples.el` file. I guess it belongs after `-first`.
