### ISSUE TITLE
Implement -cond?

### ISSUE THREAD

**Issue by wasamasa** [magnars/dash.el#126]
Today I've finally looked at `-let` in hope of shortening a function and throw away `pcase` usage. I've succeeded in that goal, however it made me wonder whether there isn't a `cond` or `case`-like statement offering the flexibility of `-let`'s pattern matching.  If there isn't, how would one go about implementing it?

**Comment by Fuco1** [comment]
`-let` can't do pattern matching, it only destructures.

Pattern matching might be bolted on top later, but it would likely end up looking like pcase because you need the syntax distinctions for symbols/forms which should be bound and symbols/forms which are values.

**Comment by wasamasa** [comment]
Well, ok, how about a destructuring `-cond` macro?

**Comment by Fuco1** [comment]
Can you show me an example how would one use it?  Because you don't really know what can go inside the cond, the destructuring might not work at all.  Consider

```
(cond
  ((= (+ 3 4) 8) ...)
  ((day-of-week "sunday") ...)
  ((vectorp x) ...)
  ((listp x) ...))
```

**Comment by wasamasa** [comment]
Ok, disregard that idea then and go for a less general case (since case-likes are provided by pcase and cl-lib in Emacs).
