### ISSUE TITLE
Multiple lists for -map, -some? etc.

### ISSUE THREAD

**Issue by politza** [magnars/dash.el#128]
Is there a reason these functions don't accept multiple sequences resp. arity functions ?

**Comment by Fuco1** [comment]
You can `-zip` the multiple lists and then pass that into `-map` or anything else.

**Comment by politza** [comment]
Shure,

    (-map (-lambda ((a . b)) (< a b))
          (-zip '(0 1 2 3)
                '(1 2 3 4)))

    (cl-mapcar '<
               '(0 1 2 3)
               '(1 2 3 4))

but why limit these functions to a single argument ?

**Comment by magnars** [comment]
When implementing it, I didn't find that multi-arity map et al. was used often enough to warrant the additional complexity.

**Comment by Fuco1** [comment]
You can do the second thing with `(-zip-with '< '(0 1 2 3) '(1 2 3 4))`

For more than two arguments, `-zip` returns a list of that many elements so you can skip the `-lambda` bit.

**Comment by politza** [comment]
So `-zip-with` is like `cl-mapcar` limited to 2 lists ?

Never mind, it's maybe just a matter of taste.

**Comment by Fuco1** [comment]
1) Yes
2) Probably also yes. Dash is not trying to be `cl` with different names. It's api is oriented to more functional-language style (clojure, haskell...)
