### ISSUE TITLE
The rails docset is not complete?

### ISSUE THREAD

**Issue by stardiviner** [magnars/dash.el#132]
I want to search the doc/api of Rails flash.

Just like this screenshot.

![emacs dash does not have some doc for rails](https://cloud.githubusercontent.com/assets/378699/6767952/81a81a8e-d08a-11e4-8e5d-23133bdae2c1.png)

But I got nothing matched in dash.el result.

![emacs dash does not have some doc for rails 2](https://cloud.githubusercontent.com/assets/378699/6767967/b7cc86ae-d08a-11e4-8a98-379d7eb1f845.png)

I tried to remove the installed rails docset, and re-install it again.

Still not solved.

Do you have any idea about this?

**Comment by magnars** [comment]
I guess you are looking for this emacs project: https://github.com/areina/helm-dash :)
