### ISSUE TITLE
-accumulate: a function that collects args that its being called with.

### ISSUE THREAD

**Issue by mpontus** [magnars/dash.el#134]
This function can be useful to help with retrieval of the collections produces by mapatoms, map-keymaps or any other place that  relay data by applying it to external function.

I don't expect them to be accepted as they are right, but I'd like at least to open up a discussion to find the most useful approach. There has to be wider range of potential applications, as I would often find myself wishing for this kind of outlet applied to my own forms.

---

Collect arguments for first argument FUNCTION. FUNCTION will be
called with single argument, which it will use to call upon with
arguments which will be added to final result. If PRED is a
function, it will determine applicable argument lists by accepting
them as only argument and returning non-nil.

```emacs-lisp
(defun -accumulate (function &optional pred)
  (let (return) (funcall function
     (function (lambda (&rest args)
       (when (or (not pred) (funcall pred args))
         (!cons args return)))))
       (nreverse return)))
```

Depending on the choice of primary function, one of the below can
add (non-)anaphoric variant to them.

```emacs-lisp
(defmacro --accumulate (form &optional pred)
  `(-accumulate (function (lambda (it) ,form)) ,pred))
```

This function enabled anaphoric form below, alas it still fails
tests and I spent a lot of time unsuccessfully trying to figure
out why.

```emacs-lisp
(defun -accumulate (function &optional pred)
  (--accumulate (funcall function it) pred))
```

Collect arguments for `it' during execution of FORM. If PRED is a
function it is called with list of arguments as a single argument to
determine if it will be included in result. It is failing tests right
now.

```emacs-lisp
(defmacro --accumulate (form &optional pred)
  (declare (debug (form lambda-form)))
  (let ((r (make-symbol "result")))
    `(let (,r) (funcall
        (function (lambda (it) ,form))
        (function (lambda (&rest args)
          (when (or (not pred) (funcall pred args))
            (!cons args ,r)))))
       (nreverse ,r))))
```

---

I've uploaded tests and code to [temporary repo](https://github.com/myeffort/dash-accumulate).

**Comment by Fuco1** [comment]
Your formatting is weird.

```elisp
(defun -accumulate (function &optional pred)
  (let (return)
    (funcall function (function (lambda (&rest args)
                                  (when (or (not pred) (funcall pred args))
                                    (!cons args return)))))
    (nreverse return)))
```

This is hardly even valid elisp.

**Comment by Fuco1** [comment]
If I understand it correctly, it could also help with simplifying this code I use to count my unread elfeed items

```elisp
(let ((n 0))
  (with-elfeed-db-visit (entry _feed)
    (when (memq 'unread (elfeed-entry-tags entry))
      (cl-incf n)))
  n)
```

I had in mind to write something to alleviate this process.  Can you see it possible with your function?

**Comment by myeffort** [comment]
Thanks, Fuco. it's how emacs-25 indents function form, not me. To your concerns of validity I can say that I adopted this pattern from dash itself, from [dash-functional](https://github.com/magnars/dash.el/blob/master/dash-functional.el#L138) to be precise. 
Regarding to your example, if I understand it correctly, you're working around forms which don't make any implicit calls. I don't think my implementation will benefit you in this case. 
I will make an at better explaining what this function does right now: 
User may specify a function which will will be ran with one argument. This argument is basically a spy-function that collects all arguments that it receives into the storage that will make up the return value expected by top-level. 
When using anaphoric form user any context he wants, but at the end it would still use spy-function, which user addresses by `it`. Only this spy-function has access to the storage, mentioned above, and it will only access it when it is invoked. 
I am primarily looking at two particular use-cases for these functions: collecting values from mapatoms and map-keymaps (the latter requires to be -rpartial'd), but I suspect there may be more subtle applications.

**Comment by Fuco1** [comment]
This looks like scheme

```elisp
(function (lambda (&rest args)
            (when (or (not pred) (funcall pred args))
              (!cons args return))))
```

In elisp you can't implicitly call a function in a variable like this because lisp-2 and all.

I think I understand what it does, but an actual example would be helpful :)

**Comment by myeffort** [comment]
Ah, no, the `function` has nothing to do with the variable `function` from
arguments.
Someone told I should always wrap lambdas inside such `function` so I am
doing it as long as it doesn't stop it from working.

**Comment by myeffort** [comment]
#### Examples:

 * This one finds all variables containing keymap:

```emacs-lisp
(-accumulate 'mapatoms
             (-applify (-andfn 'boundp
                               (-compose 'keymapp
                                         'symbol-value))))
```

 * This one finds all active *indirect* key-bindings:

```emacs-lisp
;; I'm not even sure what classifies as event-type, but this topic
;; has picked my interest (info "(elisp) Key Lookup")

(--accumulate (map-keymap it (make-composed-keymap
                              (current-active-maps)))
              (-applify (lambda (event binding)
                          (and (listp binding) (keymapp (car binding))))))
```

**Comment by occidens** [comment]
> Ah, no, the `function` has nothing to do with the variable `function` from
> arguments.
> Someone told I should always wrap lambdas inside such `function` so I am
> doing it as long as it doesn't stop it from working.

The `function` special form *is* valid Elisp, but it is superfluous to wrap lambdas in modern Elisp because `(function (lambda ...))` and `(lambda ...)` and `#'(lambda ...)` are all equivalent to the byte-compiler (this was, [apparently](http://endlessparentheses.com/get-in-the-habit-of-using-sharp-quote.html), not always the case). See [Anonymous Functions](http://www.gnu.org/software/emacs/manual/html_node/elisp/Anonymous-Functions.html) in the Elisp manual and this [StackExchange post](http://emacs.stackexchange.com/questions/3595/when-to-sharp-quote-a-lambda-expression) for more information.

If you are in doubt about how a lambda is treated, you can compare the byte-code of two snippets as shown below. The following form returns `t`:
``` emacs-lisp
(equal
 (byte-compile
  (defun -accumulate (function &optional pred)
    (let (return)
      (funcall function
	       (function (lambda (&rest args)
			   (when (or (not pred) (funcall pred args))
			     (!cons args return)))))
      (nreverse return))))
 (byte-compile
  (defun -accumulate (function &optional pred)
    (let (return)
      (funcall function
	       (lambda (&rest args)
		 (when (or (not pred) (funcall pred args))
		   (!cons args return))))
      (nreverse return)))))
```

**Comment by myeffort** [comment]
Thank you, William. Your input will reflect on my code from now on.

**Comment by alphapapa** [comment]
I'm a lisp novice, but if I understand correctly, this is supposed to be like the accumulate function described [here](https://www.cs.berkeley.edu/~bh/ssch8/higher.html), right?  e.g.:
```scheme
> (accumulate + '(6 3 4 -5 7 8 9))
32
 
> (accumulate word '(a c l u))
ACLU
 
> (accumulate max '(128 32 134 136))
136
 
> (define (hyphenate word1 word2)
    (word word1 '- word2))
 
> (accumulate hyphenate '(ob la di ob la da))
OB-LA-DI-OB-LA-DA
```

**Comment by myeffort** [comment]
No, that would be [-reduce](https://github.com/magnars/dash.el/#-reduce) function.

**Comment by Wilfred** [comment]
Hmm, this is a very interesting idea, though not something I need very often. The example implementation isn't quite right (e.g. you should use `apply` rather than `funcall` I think):

```lisp
(defun -accumulate (function &optional predicate)
  "Convert a function called for side-effects to a function that
returns a list.

E.g. instead of this:

\(let (result)
  (mapatoms 
   (lambda (item)
     (!cons item result))))

You can write this:

\(-accumulate #'mapatoms)

If PREDICATE is provided, only accumulate results where PREDICATE
returns t."
  (let (result)
    (funcall function
             (lambda (&rest args)
               (when (or (null predicate)
                         (apply predicate args))
                 (setq result (append args result)))))
    (nreverse result)))
```

**Comment by mpontus** [comment]
I'm closing this issue since I can no longer remember the use case which I was trying to address.
