### ISSUE TITLE
Wrong type argument in examples.el

### ISSUE THREAD

**Issue by jfries** [magnars/dash.el#141]
Trying to debug this with my very limited elisp foo, but wanted to post here as well. I'm using emacs24.4.1 on ubuntu.

The actual error I'm seeing is examples.el:738:1:Error: Wrong type argument
but  I did a binary search on the commit history to dash.el, and was able to determine that the error was introduced on this commit by @Fuco1 :
https://github.com/magnars/dash.el/commit/8f9fc4113d90b8f48192b56ea6d60db1bce2dc87#diff-cc3819726ff9da6c14e7d6088a309c32

the sequence I found was:
1) october 3rd commit a4be872 does not generate an error
2) october 3rd commit f0831d generated error "match form must be a list"
3) october 3rd commit 8f9fc4113 generates error "wrong type argument"
4) all commits after 8f9fc4113 generate error "wrong type argument"

**Comment by Fuco1** [comment]
What did do to produce that error? Did you find it with flycheck or did you try to compile the file?

It is actually expected that it produces the error, the form

    (-lambda a t) !!> wrong-type-argument

tests an invalid form and expects an error.  The clause expands to

```elisp
(should-error
     (eval
      '(-lambda a t))
     :type 'wrong-type-argument)
```

**Comment by Fuco1** [comment]
Anyway, closing this for now.  If you think this is a legitimate issue, please reopen.  Thanks.
