### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by bbatsov** [magnars/dash.el#149]
The last one happened a while back...

**Comment by magnars** [comment]
`2.11.0` released!

**Comment by bbatsov** [comment]
10x. You rock! :-)

**Comment by magnars** [comment]
\m/

**Comment by Fuco1** [comment]
heh, I wanted to get the current PRs in and then release.  But they aren't super important so I guess it's fine.

**Comment by magnars** [comment]
Another release after PRs is no big deal either. :)

**Comment by bbatsov** [comment]
Indeed. Release early, release often.

On Wednesday, July 1, 2015, Magnar Sveen <notifications@github.com> wrote:

> Another release after PRs is no big deal either. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magnars/dash.el/issues/149#issuecomment-117737788>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com
