### ISSUE TITLE
Request: -transpose

### ISSUE THREAD

**Issue by justbur** [magnars/dash.el#150]
An example, transform from `((1 2 3 4) (5 6 7))` to `((1 5) (2 6) (3 7) (4))`. I've used `(apply 'cl-mapcar 'list lst)` but a simple `(-transpose lst)` would be easier to understand. Thanks

**Comment by Fuco1** [comment]
Hm, you can use `-zip`, though that only goes up tho the shortest list.

What is a use-case where you'd want to have unequally long lists and perform this operation?

**Comment by justbur** [comment]
Maybe `-zip` is enough. The case is that I have `N-1` columns of equal length plus 1 that is possibly shorter. Think of columns of text that I want to transform into rows of text. I could pad the last one then use zip.

**Comment by justbur** [comment]
Never mind. Now that I think about it again, `-zip-fill` will actually cover my case well.

**Comment by Fuco1** [comment]
Good to learn there's a `-zip-fill` :D Thanks and cheers.

**Comment by justbur** [comment]
Thank you for the help
