### ISSUE TITLE
-flatten lists with nil items

### ISSUE THREAD

**Issue by doublep** [magnars/dash.el#154]
(-flatten '(nil nil nil))  ==>  nil
    (-flatten '(nil (1) nil))  ==>  (1)

This looks like a bug to me. Or if it is somehow intentional it must be documented.

Incidentally, the speed optimization in my performance pull request fixes this bug, though I didn't think about that when writing it.

**Comment by Fuco1** [comment]
This is not a bug and is quite expected.  Consider that nil is an empty list with no element in it.

**Comment by Fuco1** [comment]
This, however, is a bug

    (-flatten '((nil) (1) (nil))) => (1)

**Comment by Fuco1** [comment]
Actually no, it isn't, because flatten works recursively as much as possible. :)

**Comment by doublep** [comment]
I suggest adding this to documentation then. I understand the reasoning, but it's still somewhat confusing.
