### ISSUE TITLE
-remove-last is destructive and self-inconsistent

### ISSUE THREAD

**Issue by doublep** [magnars/dash.el#157]
(let ((l '(1 2 3)))
      (list (--remove-last (< it 3) l)
            l))

   ==> ((1 3) (1 3))

    (let ((l '(1 2 3)))
      (list (--remove-last (< it 0) l)
            l))

   ==> ((1 2 3) (1))

By contrast, `-remove-first` doesn't modify its argument, but returns a new list.

**Comment by Fuco1** [comment]
Many of these functions are implemented by reversing the list and calling forward variant.  Because I used `nreverse` everywhere the inputs are destroyed.

I guess there will be more issues like this.

**Comment by doublep** [comment]
I reported one more, but other uses of `nreverse` seem fine.

**Comment by Fuco1** [comment]
I fixed this in #158.
