### ISSUE TITLE
-map-last is destructive and self-inconsistent

### ISSUE THREAD

**Issue by doublep** [magnars/dash.el#158]
(let ((l '(1 2 3)))
      (list (--map-last (< it 3) (number-to-string it) l)
            l))

    ==> ((1 "2" 3) (1 "2" 3))

    (let ((l '(1 2 3)))
      (list (--map-last (< it 2) (number-to-string it) l)
            l))

    ==> (("1" 2 3) (1))

`-map-first` doesn't modify its argument.

**Comment by Fuco1** [comment]
Late but fixed, thanks for reporting this.
