### ISSUE TITLE
FR: -filtermap

### ISSUE THREAD

**Issue by jeberger** [magnars/dash.el#169]
It would be nice to have a `-filtermap` function (and the associated anaphoric `--filtermap`) that would create a list with the result of a predicate when this result is not `nil`. In other words, this code:

```lisp
(-filtermap 'pred l)
```

would be equivalent to this:

```lisp
(--mapcat (let ((tmp (pred it)))
            (when tmp (list tmp))))
```

**Comment by magnars** [comment]
See https://github.com/magnars/dash.el#-keep-fn-list

**Comment by jeberger** [comment]
Oops, sorry for the noise. Thanks!

**Comment by magnars** [comment]
No worries :)
tir. 8. des. 2015 kl. 11.34 skrev jeberger <notifications@github.com>:

**Comment by Fuco1** [comment]
But why mapcat in the first place?

**Comment by jeberger** [comment]
Because I somehow missed seeing `-keep` in the docs and `flatMap` is the way to do it in Scala (with a predicate returning `Option`), which translates into `-mapcat` when the predicate returns a list.

**Comment by Fuco1** [comment]
Oh, right. I forgot that a good programmer can write Haskell in any language, even if using detour over to Scala :D

(in Haskell this is mapMaybe)
