### ISSUE TITLE
--filter which returns only the non-nil values of the predicate

### ISSUE THREAD

**Issue by tarsius** [magnars/dash.el#170]
Instead of

```lisp
(--mapcat (--when-let (PRED it) (list it)) LIST)
```

or

```lisp
(-non-nil (-map PRED LIST))
```

I often would like to write

```lisp
(--map-filter PRED LIST)
```

Am I overlooking something? What do you think?

**Comment by Fuco1** [comment]
`--keep`

**Comment by Fuco1** [comment]
Heh, actually the very last issue, #169, was about this same thing :D 

@magnars Maybe we should add some alias for discoverability?

**Comment by magnars** [comment]
I guess the first move would be to move it to the **Maps** category.

**Comment by tarsius** [comment]
> Heh, actually the very last issue, #169, was about this same thing :dancer: 

I'll keep that in mind the next time someone opens a duplicate in one of my projects o_0

> I guess the first move would be to move it to the Maps category.

Mentioning it in the doc-string of `-filter` might also help.

**Comment by Fuco1** [comment]
I'm not sure about maps category as this possibly reduces the dimension, and definitely can reduce the length.  I would expect a map to not do either.  I've added a "see also" note to filter.
