### ISSUE TITLE
Add function -find-value analogous to -find-index

### ISSUE THREAD

**Issue by Wilfred** [magnars/dash.el#172]
Take a predicate pred and a list and return the the first element in the list satisfying the predicate, or nil if there is no such element.

E.g.

```
(-find-value #'odd? '(2 4 1 6 3 3 5 8)) ;; => 1
```

I'm happy to write a pull request for this. Have I missed a function that's doing this already?

**Comment by Wilfred** [comment]
Argh, it's `-first`. I'll send a docs patch, as I totally missed this.

**Comment by Fuco1** [comment]
We could possibly add an alias?

**Comment by Wilfred** [comment]
PR is merged, closing.
