### ISSUE TITLE
Any plans for inclusion of the clojure "doto" macro?

### ISSUE THREAD

**Issue by sp3ctum** [magnars/dash.el#176]
The macro, as you must surely know, works like so:

```clojure
(doto x & forms)
Evaluates x then calls all of the methods and functions with the
value of x supplied at the front of the given arguments.  The forms
are evaluated in order.  Returns x.
 (doto (new java.util.HashMap) (.put "a" 1) (.put "b" 2))
```

https://clojuredocs.org/clojure.core/doto
https://github.com/clojure/clojure/blob/clojure-1.7.0/src/clj/clojure/core.clj#L3700

If you think this might be a good idea, I can try to make an elisp port.

**Comment by Fuco1** [comment]
This is it I think

```
-> is a Lisp macro in `dash.el'.

(-> X &optional FORM &rest MORE)

Thread the expr through the forms. Insert X as the second item
in the first form, making a list of it if it is not a list
already. If there are more forms, insert the first form as the
second item in second form, etc.
```

**Comment by sp3ctum** [comment]
It's almost the same, but `->` uses the result of each previous expression in the following expression.
The difference to `doto` is that doto always uses the first value.
So in the OP, `(.put (new java.utils.HashMap) "a" 1)` returns nil (void), and yet it's possible to use the second expression. You can think of them as modifying the hashmap.

With doto it's possible to use "setters" or side effects with less code.

**Comment by Fuco1** [comment]
Oh, I see :) Java hashmap works by side effect :D  I'm getting too used to Haskell.

Very well, I guess we could add such a thing. Hopefully someone will steal it later and put it in the core.

If you want to try a PR, don't forget tests.  The readme is then autogenerated from docstring and the test-cases.

**Comment by Fuco1** [comment]
We'll continue this in the PR.
