### ISSUE TITLE
cut does not treat <> in first slot as a function

### ISSUE THREAD

**Issue by holomorph** [magnars/dash.el#185]
For example
```elisp
(mapcar (-cut <> 1 2 3) (list 'list 'vector 'string))
```
fails.

I suggest checking PARAMS and conditionally prepending funcall:
```elisp
(if (eq (car params) '<>) (setq params (cons 'funcall params)))
```
Edit: that would also mean small fixes to `-orfn` and `andfn`

**Comment by Fuco1** [comment]
I'm not sure this is what cut is supposed to do.  It creates partially applied functions (that is, filling in arguments), you are not filling in arguments.

This works:

    (mapcar (-cut (lambda (f a b c) (funcall f a b c)) <> 1 2 3) (list 'list 'vector 'string))

Of course you know that...  I'll have to think about it, but it doesn't make much sense when you can just write

    (--map (funcall it 1 2 3)  (list 'list 'vector 'string))

**Comment by holomorph** [comment]
I suppose it comes down to whether or not you want `-cut` to behave as in Scheme, i.e. whether you think it makes sense to be able to write things like in a Scheme.  The additional shorthand of not having to write funcall seems nice to me.

**Comment by Fuco1** [comment]
I think I'll do what you suggested in the OP.  This was modelled after SRFI 26 so I think we should have it compatible.  I should also add the rest slot while at it.  Or do you want to PR?

**Comment by holomorph** [comment]
Nah, my PR would just be the one line in the original post anyways. Go ahead

**Comment by Fuco1** [comment]
Done.  Thanks for the idea.

**Comment by holomorph** [comment]
o/
