### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by Wilfred** [magnars/dash.el#190]
I'm currently depending on --each-indexed in suggest.el, but this isn't available in MELPA stable yet. https://github.com/Wilfred/suggest.el/issues/4#issuecomment-239348115

Could you tag a new release?

**Comment by Wilfred** [comment]
The changelist in the readme doesn't show it, but there are other new features in master that haven't been tagged yet, such as `-select-column`.

**Comment by magnars** [comment]
I'd be happy to tag up a new release. I'm a bit low on time - would you mind stitching together the change log? If I could just paste that into the readme, I'll get to the rest quite quickly.

**Comment by magnars** [comment]
`2.13.0` released. Thanks for the help!
