### ISSUE TITLE
curly quotes conflict with emacs 25 defaults

### ISSUE THREAD

**Issue by holomorph** [magnars/dash.el#192]
I feel like I've run into this before, but doing `sh create-docs.sh` will yield

```
dash.texi:344: unexpected @
```

in emacs master.  I have worked around it by adding

```
(setq text-quoting-style 'grave)
```

in the top level of `dev/examples-to-info.el`

**Comment by Fuco1** [comment]
Should we guard this with a version check or can I just pop the form there?

**Comment by holomorph** [comment]
I think you can just put the form there; I guess batch emacs does not complain about setting void variables:
```
$ emacs --batch --eval "(setq heyooooooo nil)"
```
doesn't complain
