### ISSUE TITLE
permutation and power set

### ISSUE THREAD

**Issue by holomorph** [magnars/dash.el#196]
Hi, not sure if y'all care for more set logic or some combinatorics, but I had a need for these recently and thought I'd drop them here.  Of course, these would be a bit different written using dash.

```
(defun powerset (s)
  "Return the power set of S."
  (if (null s) '(())
    (let ((prev (powerset (cdr s))))
      (append (mapcar (lambda (elt) (cons (car s) elt)) prev)
              prev))))

(defun permutations (s)
  "Return the permutations of S."
  (if (null s) '(())
    (apply #'append
           (mapcar (lambda (x)
                     (mapcar (lambda (perm) (cons x perm))
                             (permutations (remove x s))))
                   s))))
```

**Comment by Fuco1** [comment]
I was thinking about this on Monday.  I'm going through my notes and this has been sitting there for some time.  If you cook up a PR I'll be fine with including it.
