### ISSUE TITLE
Annotate functions as pure and side-effect free

### ISSUE THREAD

**Issue by Wilfred** [magnars/dash.el#198]
These annotations help the byte-compiler do clever things like compile-time function execution. Since dash.el functions are often pure and side-effect free, this could be a good performance win.

I'm happy to whip up a patch.

**Comment by magnars** [comment]
Sounds good!

**Comment by Fuco1** [comment]
The real question here is why didn't we do this 3 years ago :D Go ahead!

**Comment by Wilfred** [comment]
Note that downstream consumers of dash.el will now get warnings for unused results of pure functions. However, these won't occur in dash.el itself. See http://emacs.stackexchange.com/a/28341/304 if you're interested.
