### ISSUE TITLE
-table-flat returns nil when the length of LISTS is 1.

### ISSUE THREAD

**Issue by kawabata** [magnars/dash.el#202]
It seems '-table-flat' function returns 'nil' when its length of LISTS argument is 1.

For example,

(-table-flat '+ '(2))
should return '(2), but it returns nil.

(-table-flat '+ '(2) '(2))
properly returns '(4).

Regards,

**Comment by Fuco1** [comment]
Yep, that's a bug.  We can take the defining equation to be 

    (-flatten-n (1- (length lists)) (apply '-table fn lists))

which properly computes `(2)`
