### ISSUE TITLE
Consider adding a -range or -iota function wrapping or aliasing number-sequence from subr.el

### ISSUE THREAD

**Issue by davidshepherd7** [magnars/dash.el#207]
It's nice to have all list functions in one place for discoverability.

`range` is the name for this function in [python](https://docs.python.org/3/library/functions.html#func-range) and [clojure](https://clojuredocs.org/clojure.core/range), and IMO is the better name.

`iota` is the name in [APL, Go](https://en.wikipedia.org/wiki/Iota) [C++](http://en.cppreference.com/w/cpp/algorithm/iota) and [scheme](http://stackoverflow.com/questions/12909856/analog-of-pythons-range-in-scheme).

I can't find if this function exists in Haskell (I guess people just use the shorthand notation) or common lisp.

**Comment by holomorph** [comment]
FWIW i wrote this some time ago.  The docstring is taken from the Guile reference manual
``` elisp
(defun iota (count &optional start step)
  "Return a list containing COUNT numbers.
Starts from START and adds STEP each time.  The default START is
zero, the default STEP is 1.  For example,

    (iota 6)        => (0 1 2 3 4 5)
    (iota 4 2.5 -2) => (2.5 0.5 -1.5 -3.5)

This function takes its name from the corresponding primitive in
the APL language."
  (if (or (not (integerp count)) (< count 0))
      (signal 'wrong-type-argument count))
  (if (and step (zerop step)) (make-list count start)
    (let ((res '())
          (x (or start 0))
          (dx (or step 1)))
      (while (<= 0 (setq count (1- count)))
        (push x res)
        (setq x (+ x dx)))
      (nreverse res))))
```

**Comment by Fuco1** [comment]
@holomorph is that different from `number-sequence`?

**Comment by Fuco1** [comment]
@davidshepherd7 @holomorph Do you want to cook up a pull request?

**Comment by neeasade** [comment]
For future searchers -- I'm currently using this, which I think matches the clojure impl:

```
(defun range (one &optional two step)
  (let* ((start (if two one 0))
          (end (if two two one))
          (step (or step (if (> end start) 1 -1))))
    (cond
      ((= end start) (list start))
      ((> end start)
        (number-sequence start (- end 1) step))
      ((< end start)
        (number-sequence start (+ 1 end) step)))))
```
