### ISSUE TITLE
error: Required feature `dash' was not provided

### ISSUE THREAD

**Issue by zobbo** [magnars/dash.el#208]
For info, I've installed Prelude twice today, first of all on Ubuntu 16.10 with no issues and secondly with Linux Mint Cinnamon (18.1) where I got the error after install of:

     error: Required feature `dash' was not provided

I solved the issue on Mint by installing dash via apt

    `apt-get install dash-el`
Emacs was installed by apt - `emacs-version` gives 24.5.1

**Comment by Fuco1** [comment]
You should not install emacs packages via `apt` as that does not check dependencies of emacs pacakges properly.  Use package.el to install all emacs packages.

In either case, this is not a dash "issue".  Installing prelude via package.el pulls all the dependencies, so you probably installed it via apt where the dependency was not declared.

**Comment by zobbo** [comment]
Installed what via apt?

I have installed prelude many times in the same way and as I said, installed Prelude on a clean install of Ubuntu (16.10) earlier today without the issue. 

I installed mint, installed Emacs via apt and then installed prelude using the normal script. full stop.

I installed dash-el to fix my issue - I am not saying that's the solution, merely how I solved my issue.
