### ISSUE TITLE
--> doesn't insert `it` if `it` isn't at the top level of a form

### ISSUE THREAD

**Issue by zck** [magnars/dash.el#218]
I'm using version 2.13.0 of dash.

I had a call to `-->` where I inserted `it` as not the top-level element of a form, but a secondary one. Sample code:

    (--> 3
         (car (list it)))

I would expect this code to return `3`, but it instead errors:

    *** Eval error ***  Symbol’s value as variable is void: it

It works if I only insert `it` at the top-level of the forms:

    (--> 3
         (list it)
         (car it))

**Comment by magnars** [comment]
Yes, this is a known limitation of the threading macros.

**Comment by zck** [comment]
Ah. Is this by design, or would you be open to making the macro replace `it` anywhere in the forms?

**Comment by Fuco1** [comment]
It would be madly difficuly because you can use other anaphora inside the `-->` which would mean resolving scopes and all sorts of difficulties.  Not impossible, but probably not worth it.

Usually it is possible to "unwrap" the forms manually into a series of arguments to the macro, in your case `(--> 3 list car)`

**Comment by zck** [comment]
I might play around with some stuff and investigate this. It was a pretty unexpected error.

Could this at least be put in the documentation?

**Comment by magnars** [comment]
The threading macros work like in Clojure, and are very straight forwardly implemented. Something like this would both break with the original API, make the implementation much worse, and not really be useful. So this change is not wanted.

**Comment by zck** [comment]
Clojure's `as->` doesn't have the limitation discussed here. Several examples of this are in the [Clojure documentation](https://clojuredocs.org/clojure.core/as-%3E#example-56d7421ae4b0b41f39d96cdb).

Or look at [this example](https://repl.it/IGM4/0), which is exactly the code I put above (with the difference in naming, and the explicit variable name).

**Comment by magnars** [comment]
Well, paint me surprised. And wrong. Sorry about that. In that case, I would be more amenable to this change.
