### ISSUE TITLE
Warnings for pure and side-effect-free properties

### ISSUE THREAD

**Issue by arichiardi** [magnars/dash.el#226]
Hello folks!

I have a strange series of warnings when I launch `cask` in the project or compile `magit` against latest master. It looks like something changed here and I have no clue of what it is:

```
/.emacs.d/packs/dev/foundation-pack/vendor/submodules/dash ((2.13.0-31-gb4faa93) %)$ cask
Warning: Unknown defun property `pure' in -remove-item
Warning: Unknown defun property `side-effect-free' in -remove-item
Warning: Unknown defun property `pure' in -non-nil
Warning: Unknown defun property `side-effect-free' in -non-nil
Warning: Unknown defun property `pure' in -replace
Warning: Unknown defun property `side-effect-free' in -replace
Warning: Unknown defun property `pure' in -replace-first
Warning: Unknown defun property `side-effect-free' in -replace-first
Warning: Unknown defun property `pure' in -replace-last
Warning: Unknown defun property `side-effect-free' in -replace-last
Warning: Unknown defun property `pure' in -flatten
Warning: Unknown defun property `side-effect-free' in -flatten
Warning: Unknown defun property `pure' in -flatten-n
Warning: Unknown defun property `side-effect-free' in -flatten-n
Warning: Unknown defun property `pure' in -concat
...many many more...
```

I think I need some help.

```
$ emacs -version
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by Fuco1** [comment]
Hi, thanks for reaching out!

The problem is that those properties are only defined in Emacs 25+, they help the compiler with better optimization.  I think there's not much to do for the older Emacsen.

Do the warnings cause you some serious trouble (e.g. breaks builds etc.)  In that case we could probably add some guards on the Emacs version but if not I wouldn't bother as more and more people will gradually migrate to 25 (it's been out for quite a while but myself I only switched about a month ago so I understand the sentiment of "never upgrade if it works" quite well)

**Comment by arichiardi** [comment]
Oh ok sounds good. Well it has slowed down loading of some packages quite a bit (`magit` in particular seems super slow, see https://github.com/magit/magit/issues/3135). Orders of magnitude slower :smile: I guess I will upgrade as soon as I have some free time. No breakage fortunately.

**Comment by tarsius** [comment]
I strongly doubt that these properties cause the slowdown when compiling magit. It is much more likely that this is caused by the known ["tramp goes and has a smoke issue"](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20015).

**Comment by arichiardi** [comment]
So this one can be closed I think. Thanks to both!
