### ISSUE TITLE
process-output-as-string macro?

### ISSUE THREAD

**Issue by alphapapa** [magnars/dash.el#229]
Maybe it's just me, or maybe I don't know a better way yet, but it seems like every time I need to call a process on a string and get its output, I have to refer to docs to make sure I'm calling the functions correctly.  What do you think about a macro like this (name TBD):

```el
(cl-defmacro process-output-as-string (process &optional &key args stdin)
  "Return string of output of PROCESS called with ARGS and STDIN.
ARGS and STDIN are optional.  ARGS may be a string or list of
strings.  STDIN should be a string.  If process returns non-zero,
raise `user-error' with STDERR message."
  (declare (indent defun))
  (setq args (internal--listify args))
  `(with-temp-buffer
     ,(when stdin
        `(insert ,stdin))
     (unless (= 0 (call-process-region (point-min) (point-max)
                                       ,process t '(t t) nil
                                       ,@args))
       (user-error (concat ,(concat process " failed: ")
                           (buffer-string))))
     (buffer-string)))
```
Called like:
```el
(process-output-as-string "grep"
  :args "macro"
  :stdin "defmacro")  ; => "defmacro" 
(process-output-as-string "grep"
  :args ("-e" "^macro")
  :stdin "defmacro") ; => "grep failed: "
```

**Comment by Fuco1** [comment]
I can see this being useful but it feels very much out of scope of this library.  Maybe something like [crux](https://github.com/bbatsov/crux) is a better fit.

**Comment by Fuco1** [comment]
By the way, why a macro? This can be a function.

**Comment by alphapapa** [comment]
Because `call-process-region` does not accept a list of arguments, so the list must be spliced into it.  And AFAIK there's no way to use keyword args and `&rest` together, so you either use keyword args or you use `&rest`, and if you use keyword args you have to splice them in.

**Comment by Fuco1** [comment]
But dash is a list processing library at its core, not a better api library.  If there isn't such a project then we can start one, but already I feel dash is overflowing in some cases its intended scope (the control macros or arrows feel quite out of place for example).

**Comment by alphapapa** [comment]
Ok, thanks.

Yeah, I'd be interested in such a project.  :)

**Comment by basil-conto** [comment]
@alphapapa For what it's worth, I often find the built-in function `process-lines` more convenient than using `call-process` directly for simple use-cases.

**Comment by alphapapa** [comment]
@basil-conto Thanks, I did not know about that function.  Looks very useful.
