### ISSUE TITLE
-remove-at does not match its docs

### ISSUE THREAD

**Issue by Wilfred** [magnars/dash.el#231]
`-remove-at` is grouped under "Bag of various functions which modify input list."

However, it doesn't actually modify the list:

```emacs-lisp
(setq wh/x (list 1 2 3 4 5))
(-remove-at 1 wh/x)
wh/x ;; => (1 2 3 4 5)
```

Is this section of functions just general list-to-list functions, or is the function in the wrong section?

**Comment by Fuco1** [comment]
Well, all of those functions are (should be!) pure, I suppose it's just badly described.
