### ISSUE TITLE
Infinite loop in -interleave and -zip

### ISSUE THREAD

**Issue by Wilfred** [magnars/dash.el#241]
Both of these functions go into an infinite loop when called with zero arguments. `(-interleave)` and `(-zip)`.

**Comment by Fuco1** [comment]
Heh, there's a condition `while (-none? 'null lists)` and `-none?` always returns `t` on empty lists (there are no elements to test so it is true that all elements do not satisfy the condition).

I think I'll change the signatures of both `-zip` and `-interleave` to `(list &rest lists)`, I don't see any reason to call it with no arguments.

What do you think?

**Comment by Fuco1** [comment]
Hm, no.  That would make the docs more complicated.  I'll just add a check to see if anything was passed in.

Saying "zip list with lists" or something similar might be confusing.
