### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by Wilfred** [magnars/dash.el#243]
I'd like to use -permutations but the last tag is before the relevant PR was merged.

**Comment by Fuco1** [comment]
I'll try to prepare the release log on the weekend, @magnars do you agree?  There has been quite a lot of new things so I think a release is reasonable.

**Comment by Fuco1** [comment]
I would also like to maybe finally drop E23 support.  I've written a bunch of new functions which depend on closures and can't put them in :(  

It's been over 5 years since 24.1 was released (10 Jun 2012) so I think the affected user base is going to be negligible by now.

**Comment by magnars** [comment]
Agreed.

On the support of E23: Can we include the new functions (that will not work on E23) without breaking old functions? IE, offer new features without breaking old ones?

**Comment by Fuco1** [comment]
The new functions won't break anything that exists already, they are simply new functions using closures.  I can optionally wrap them with a version check so they won't be available on older versions.

I've rewritten some hacked functions to use closures instead of `lexical-let` macros but we can optionally wait with those.

**Comment by magnars** [comment]
👍
ons. 11. okt. 2017 kl. 13.09 skrev Matus Goljer <notifications@github.com>:

**Comment by ccharles** [comment]
Is this still on the agenda? I'd like to see `-as->` included in a stable release for [`emacs-python-pytest`][1].

[1]: https://github.com/wbolster/emacs-python-pytest/issues/2

**Comment by Fuco1** [comment]
Done in e9919f6db4d273eae50c5a73b98ddc87cf61afc8

Here's an announcement, feel free to spread the word https://twitter.com/Fuco1337/status/984531998055256064 (shameless plug)

**Comment by wbolster** [comment]
thanks @Fuco1!
