### ISSUE TITLE
Add lazy data structures

### ISSUE THREAD

**Issue by johnw42** [magnars/dash.el#246]
I've already implemented a "fix" for this issue, but this seems like the easiest way to start a discussion.

What I have is a module I'm calling "dash-lazy.el", which implements lazy lists somewhat like what you'd find in Haskell (and even more like what's in Clojure), where the contents of the list are evaluated only at the point where they are needed to traverse the list. I've made lazy versions of most of the main dash.el functions with the same name, plus a "-lazy" or "-force" prefix, depending on whether they produce a lazy output or just convert a lazy input to a non-lazy output. I've also added integration with the new "generator" mechanism in Emacs, as well as the CL loop facility.

I'm prepared to release the module on my own, but I think including it with the dash "brand" would do a lot to get people using it. If you'd rather not not include my functionality, I'll be happy to adjust the names before releasing anything so it's clear my functions aren't part of dash.

**Comment by magnars** [comment]
Sorry about the lack of response here until now. I think lazy seqs are very cool, but I don't think they fit in dash now. Thanks for the offer tho. :) Best of luck!

**Comment by decadent** [comment]
@johnw42 Is your code available anywhere? I'd like to fiddle with generators at least for my code and to have some dash-like functions for that, so not reinventing the wheel would be nice. If the experience turns out okay, perhaps the functions could really be released on Melpa.

**Comment by basil-conto** [comment]
Note that the best way to integrate different types of sequences with Emacs nowadays, is to use the generic `seq.el` API that was introduced in Emacs 25. See, for example, how lazy streams are integrated in `stream.el`: http://elpa.gnu.org/packages/stream.html.

[Emacs 25 also introduced `thunk.el` for conveniences around unevaluated thunks.]

**Comment by basil-conto** [comment]
If neither of these options quite fit the bill for you, I'd recommend either submitting patches for `seq.el`/`stream.el`, or submitting a new package to either Emacs or GNU ELPA, rather than splintering useful functionality over various forks in MELPA.

**Comment by johnw42** [comment]
@decadent I put the code up in a repository [here](https://github.com/johnw42/dash-lazy). It has more dependencies than it needs because I mostly just wrote it for my own amusement, but I think I included all the files it depends on.

**Comment by decadent** [comment]
@johnw42 Thanks! I've forked and downloaded the repo—in case you later decide you need to clean it up =)

Though I'll indeed take a closer look at the `seq` lib that Basil mentioned—I've seen it before and used some of it but it didn't occur to me that it might work for generators.
