### ISSUE TITLE
Reorder macros in such a way that they are defined before used

### ISSUE THREAD

**Issue by Fuco1** [magnars/dash.el#247]
Right now flycheck/emacs compiler complains about some macros being defined too late.  We should reorder the code in such a way that everything is defined before used.

(for example `-let*`)

**Comment by basil-conto** [comment]
Is this still the case?  I don't use Flycheck, but byte-compiling Dash does not result in any warnings.

**Comment by basil-conto** [comment]
Closing until further notice.
