### ISSUE TITLE
-keep-first: Return the first result for an x in LIST where (PRED x) is non-nil, else nil.

### ISSUE THREAD

**Issue by tarsius** [magnars/dash.el#252]
I often with there was a form that is a combination of `-keep` and `-first`.

* `-keep` Return a new list of the non-nil results of applying fn to the items in list.
* `-first` Return the first x in list where (pred x) is non-nil, else nil.
* **`-keep-first`** Return the first result for an x in list where (pred x) is non-nil, else nil.

Does that already exist and I just cannot find it?

**Comment by tarsius** [comment]
Not sure I like the name `-keep-first`, maybe call it `-match` instead?

**Comment by basil-conto** [comment]
Is this not the same as [`-some`](https://github.com/magnars/dash.el#-some-pred-list) in `dash.el`, [`seq-some`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Sequence-Functions.html#index-seq_002dsome-459) in `seq.el` and [`cl-some`](https://www.gnu.org/software/emacs/manual/html_node/cl/Mapping-over-Sequences.html#index-cl_002dsome-102) in `cl-lib.el`?

**Comment by tarsius** [comment]
Indeed. I knew this must already exist, but somehow I always though `-some` was an alias for `-filter`.

**Comment by Fuco1** [comment]
Yea, I don't like the name `-some` either, I often forget about it :/
