### ISSUE TITLE
dash-functional.el test suite fails against Emacs 26.1

### ISSUE THREAD

**Issue by spwhitton** [magnars/dash.el#278]
Debian is transitioning from Emacs 25.2 to Emacs 26.1 and we observed that dash-functional's test suite fails against Emacs 26:

    Ran 148 tests, 147 results as expected, 1 unexpected (2018-12-18 12:20:51+0000)

    1 unexpected results:
       FAILED  -prodfn

[A full log is downloadable from here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916806).

Replacing calls to `string-to-int` with `string-to-number` fixes it.

**Comment by basil-conto** [comment]
I haven't seen the reported error in a while, and the test suite has been passing on all Emacs versions between 24-27 since #309 landed, so I think this issue can be closed.
