### ISSUE TITLE
Anaphoric -doto

### ISSUE THREAD

**Issue by yyoncho** [magnars/dash.el#281]
(might be named  `--with`)

``` emacs-lisp
;; without doto...
(let ((map (make-sparse-keymap)))
  (define-key map [mouse-1]
    (lambda () (interactive) ... ))
  map)

(defmacro --doto (form &rest list)
  (declare (debug (form body))
           (indent 1))
  `(let ((it ,form))
     ,@list
     it))

;; using --doto
(--doto (make-sparse-keymap)
  (define-key it [mouse-1]
    (lambda () (interactive)...)))
```

**Comment by Fuco1** [comment]
Is this any different than `-->`? Also I'm not sure it's a good idea to return `it` always, I would naturally expect the last form.

**Comment by yyoncho** [comment]
``` emasc-lisp
;; `-->`  example
(--> (make-hash-table)
     (puthash 1 1 it))
;; => 1 
(--doto (make-hash-table)
     (puthash 1 1 it))
;; => hashtable
```

> Also I'm not sure it's a good idea to return it always, I would naturally expect the last form.

What I am looking for is `prog1` which binds the first form to a symbol. An alternative name is `--prog1`. Also, `-doto` also returns the value from the first form so it make sense `--doto` to do the same.

**Comment by Fuco1** [comment]
Eh, I didn't know `-doto` existed.  With that in mind and seeing how it works this is OK with me.

I will accept the above code as a PR if we also can add tests and a docstring.

**Comment by alphapapa** [comment]
> What I am looking for is prog1 which binds the first form to a symbol. 

The `anaphora` library provides that as `aprog1`.
