### ISSUE TITLE
Feasibility of using macros to avoid lambdas

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [magnars/dash.el#292]
I've read (most notably in Chris Wellon's [blog post](https://nullprogram.com/blog/2017/01/30/)) that elisp does not have the capability to inline lambdas and that because of this `map` functions should not in be used in performance-critical operations. 

Yet I've always wondered whether a macro can get around this for us.

What I mean is that if `map!` is a macro, perhaps this:
```
(map! (lambda (x) (+ 2 x)) '(1 2 3 4))
```
Could expand to:
```
(cl-loop for x in '(1 2 3 4) collect `(+ 2 ,x))
```
I suspect that the hard part of implementing `map!` would be making sure you replace the right parts of the lambda body in tricky lambdas like this one:

```
(lambda (x) (let ((x 1)) (+ 2 x)))
```
I think that such a macro would be excellent because we could have the nice `map` syntax while optimizing performance. Yet I haven't found any talk of doing this online. Am I missing something?

**Comment by basil-conto** [comment]
> I've read (most notably in Chris Wellon's blog post) that elisp does not have the capability to inline lambdas and that because of this `map` functions should not in be used in performance-critical operations.

I don't think it's wise or correct to make sweeping statements like that. Note that `mapc` is written in C, whereas `dolist`, `cl-loop`, etc. are implemented in Elisp, so it's unclear whether the `funcall` overhead always trumps the loop's. "Optimisations" in performance-critical code should always be backed up by profiling benchmarks; I'd be interested to see some for this example.

**Comment by Luis-Henriquez-Perez** [comment]
> Note that mapc is written in C, whereas dolist, cl-loop, etc. are implemented in Elisp, so it's unclear whether the funcall overhead always trumps the loop's.

I had not considered this. Here I've been preferring `cl-loop` over `mapcar` in my `.emacs` for speed and it may have been for nothing!  

> I'd be interested to see some for this example.

I'll post some benchmarks for this example. Though based on [these results](https://gist.github.com/Wilfred/d51db0a1433ec4abdbca58a0dec039a5) with a similar example I'd guess `mapcar` is faster.

I will investigate this further to see if one method is always faster than the other or, if not, what circumstances determine which method is faster.

In the meantime, because it is not certain whether what I suggested with `map!` is even worth doing, I am closing this issue but will re-open it if I find something interesting.

**Comment by Fuco1** [comment]
Performance critical code means you are doing over 10 million iterations.  I find it very hard to imagine what of that scale could you possible do in your init file.

Chris is a C programmer as well and he likes to get deep down to how things work.  This does not mean it is always, if ever, necessary to even think about it.

**Comment by basil-conto** [comment]
> Chris is a C programmer as well and he likes to get deep down to how things work.

Knowing how things work can only get you so far; without profiling, it's not that far from speculation.

> This does not mean it is always, if ever, necessary to even think about it.

Agreed. I'd be surprised if there's code out there that sees any meaningful speedup when switching from `mapc` at al. to `dolist` et al., at least in recent versions of Emacs.

**Comment by Fuco1** [comment]
@basil-conto I ment that he often writes articles which are quite theoretical and while correct and interesting, not very practical.  Which is not to say knowing the low level is useless, far from it.  But yes, [profile first](https://fuco1.github.io/2018-08-12-WAR-STORY:-When-turning-to-the-profiler-turns-out-to-be-a-good-call.html).

**Comment by basil-conto** [comment]
@Fuco1 Right, though I never implied anything about the usefulness of different domains of knowledge.

A tiny nit re: the article you linked: `line-number-at-pos` (via `count-lines`) almost never performs a regexp search for newlines. This is only the case when `selective-display` is `t`, which has been deprecated for a while. `count-lines` (via `forward-line`) actually use's the buffer's `newline_cache` to find newline positions.
