### ISSUE TITLE
`-cut` should act more like other function combinators by evaluating first argument 

### ISSUE THREAD

**Issue by cireu** [magnars/dash.el#293]
Instead of `(-cut + <> 1)`, `(-cut #'+ <> 1)` would be more flexible and less confusing

**Comment by magnars** [comment]
We’re not doing any breaking changes, but if -cut could be changed to
accept both forms, that is ok by me.

søn. 31. mar. 2019 kl. 04:39 skrev Zhu Zihao <notifications@github.com>:

**Comment by cireu** [comment]
well, thanks for your reply.
