### ISSUE TITLE
Add -combinations

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [magnars/dash.el#297]
I've looked through the dash library but couldn't find a function that does this. 
```elisp
(defun -combinations (&rest lists)
  "Returns a list of lists with possible combinations of elements in list.
For example, (-combinations (1 2) (3 4 5)) returns ((1 3) (1 4) (1 5) (2 3)
  (2 4) (2 5)). These are the same combinations we'd get from doing a nested
  loop with the lists."
  (declare (pure t) (side-effect-free t))
  (if (endp lists)
      (list nil)
    (mapcan (lambda (inner)
              (mapcar (lambda (outer) (cons inner outer))
                      (apply #'-combinations (cdr lists))))
            (car lists))))
```
For me at least, the main use of this function would be to flatten out nested loops.

For example, 

Instead of this:

```elisp
;; example 1
(mapcan (lambda (i)
          (mapcar (lambda (j) (+ i j))
                  '(3 4 5)))
        '(1 2))

;; or
;; example 2
(cl-loop for i in '(1 2)
         append (cl-loop for j in '(3 4 5)
                         collect (+ i j)))
```
We could write this:
```elisp
(mapcar (-lambda ((i j)) (+ i j)) (-combinations '(1 2) '(3 4 5)))
```
Here make these loops just one line and to my eyes much less complex. 

Note that for simplicity these examples use only doubly nested loops. But the case for using `-combinations` becomes even stronger when N nested loops where n is 3 or greater. With `-combinations`, its as simple as adding another list like so:

```elisp
(mapcar (-lambda ((i j k)) (+ i j k)) (-combinations '(1 2) '(3 4 5) '(7 8 9)))
```
Imagine doing this with example 1 or 2.

**Comment by Fuco1** [comment]
We have `-table` and friends, isn't that what you want?  Usually this is called "outer product" and I think it is called that in the docstring.

**Comment by Luis-Henriquez-Perez** [comment]
You're right. Thanks, I didn't realize `-table` could be used for this.
