### ISSUE TITLE
dash-enable-font-lock is defined after dash--enable-fontlock 

### ISSUE THREAD

**Issue by a13** [magnars/dash.el#298]
I extensively use use-package possibilities to keep [my config](https://github.com/a13/emacs.d) clean and declarative, one of my favorite keywords is `:custom`, so I don't have to mutate all customizables myself, just tell "I want it to be this" (I know it's just a sugar, but anyway).

The thing is when Im trying to do smth like

```el
(use-package dash
  :ensure t
  :custom
  (dash-enable-fontlock t))
```

I get an error since it's expanded to (shortened)

```el
(progn
  (customize-set-variable 'dash-enable-fontlock t "Customized with use-package dash")
  (if
      (not
       (require 'dash nil t))
      (display-warning 'use-package
                       (format "Cannot load %s" 'dash)
                       :error)))
```

and since dash-enable-font-lock is not defined before 'dash-enable-fontlock setter,I get an error

Moving dash--enable-fontlock and dash-enable-fontlock declarations after dash-enable-font-lock solves the issue.

Thanks

**Comment by Fuco1** [comment]
Would you be interested in a PR?

**Comment by basil-conto** [comment]
Please test whether #311 fixes this issue.
