### ISSUE TITLE
Adding -map-cond

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [magnars/dash.el#301]
There's a `-map-when` which is very useful albeit a bit limited. Often I find myself wanting to change elements of a list in different ways based on different conditions. So I thought maybe `map-cond` might be useful.

```elisp
(-map-cond '((stringp upcase)
             (floatp 1+)
             (numberp 1-))
           '(1 "hi" 5 "ho" .4))

;; => 
(0 "HI" 4 "HO" 1.4)

(--map-cond (((stringp it) (upcase it))
             ((numberp it) (1+ it)))
            '(1 "hi" 5 "ho" .3))

;;=>
(2 "HI" 6 "HO" 1.3)
```

This is an implementation.
```elisp
;; function
(defun -map-cond (conds list)
  (--map
   (-if-let ((_ action)
             (-first (-lambda ((pred _)) (funcall pred it))
                     conds))
       (funcall action it))
   list))

;; macro
(defmacro --map-cond (conds list)
  (let ((conds (-snoc conds '(t it))))
    `(mapcar (lambda (it) (cond ,@conds)) ,list)))

;; alternative implementation based on`-map-cond`
(defmacro --map-cond (conds list)
  `(-map-cond ',(-map (lambda (clause) (--map `(lambda (it) ,it) clause))
                      conds)
              ,list))
```

**Comment by Fuco1** [comment]
This is essentially the same as wrapping the forms in a lambda or a `cond` if you are using anaphora.  I think it's not worth extending the api for saving a tiny bit of typing.  It makes things less obvious and the api already is pretty bloated in a way.

**Comment by Luis-Henriquez-Perez** [comment]
> This is essentially the same as wrapping the forms in a lambda or a cond if you are using anaphora

I agree. Actually, I was hesitant creating this issue for this reason. But then I thought you could say the same thing about `-map-when`. So I figured I'd mention it.
