### ISSUE TITLE
Don't use font-lock-keyword-face for functions

### ISSUE THREAD

**Issue by stepnem** [magnars/dash.el#303]
As a rule, only macros and special forms are highlighted as keywords in Emacs Lisp mode. dash.el breaks this convention by highlighting everything, including functions. Please don't do this, it's confusing (it's useful to distinguish functions from macros for obvious reasons, notably evaluation of arguments and usability in higher order functions; I found it surprising that such a widely used library aimed at functional programming style should commit this error in the first place).

**Comment by Fuco1** [comment]
There's a setting to turn it off `dash-enable-fontlock`.  The default value will probably not change.

**Comment by basil-conto** [comment]
Perhaps `dash-enable-fontlock` could be extended to allow for multiple levels of font lock; see [`(elisp) Levels of Font Lock`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Levels-of-Font-Lock.html).

It could default to the highest level for backward compatibility, and lower levels could omit fontification of functions and special variables.

If this idea is welcome, I can provide a PR within a week or so, if no-one beats me to it.

**Comment by stepnem** [comment]
I don't think this is relevant. You simply don't font lock elisp
functions with font-lock-keyword-face, ever (only macros and special
forms). That's why I was so surprised dash.el does it (and the reactions
this is getting so far only continue to surprise me).

On another note, the whole dash-enable-fontlock thing seems obsolete, as
recent Emacsen do the proper fontification automatically.

**Comment by basil-conto** [comment]
> I don't think this is relevant.

Why not?

> You simply don't font lock elisp functions with font-lock-keyword-face, ever (only macros and special forms).

Can you please point me to some documentation that contains this edict?

Not only has that ship has sailed, but different modes are free to highlight whatever they consider significant, at different font lock levels. (Granted, `dash.el` does not currently come with an optional minor mode to allow toggling this behaviour, but it could, as part of my suggestion above.)

The question is where can we strike a balance/compromise between the current behaviour (that the maintainers seem to want to keep) and a less intrusive default that is more consistent with `emacs-lisp-mode` (which is what you are asking for, and which I sympathise with).

> That's why I was so surprised dash.el does it (and the reactions this is getting so far only continue to surprise me).

The extent of your surprise probably won't accelerate progress on this issue. ;)

> On another note, the whole dash-enable-fontlock thing seems obsolete, as recent Emacsen do the proper fontification automatically.

Proper fontification of what? The `dash-enable-font-lock` machinery currently fontifies function names and special variables in addition to macro names. I should have Emacs 24 and 25 sitting in a VM somewhere so I can check how different versions behave before proposing a patch.

**Comment by basil-conto** [comment]
> The `dash-enable-font-lock` machinery currently fontifies function names and special variables in addition to macro names.

I'll also see if I can limit the special variable highlighting to the bodies passed to Dash macros, but no promises. ;)

**Comment by stepnem** [comment]
>> I don't think this is relevant.
>
> Why not?

Because we're not talking about a new major mode where you define your
own font locking, we're talking about emacs-lisp-mode and your library
being (or not) a good Emacs citizen, so to speak.

>> You simply don't font lock elisp functions with
>> font-lock-keyword-face, ever (only macros and special forms).
>
> Can you please point me to some documentation that contains this edict?

I can't. I'm not aware of the "edict" being written anywhere. I guess
most people just get it. But if you still don't get it and my original
explanation didn't suffice, here are a few further points: Have a look
at how Emacs (core, although in about 10 years I've been using Emacs I
don't remember ever seeing anyone else break this convention) does elisp
font locking. Didn't it ever seem strange to you that function names are
not highlighted? If not, now that I pointed that out, why do you think
it is so? The difference between macros and functions in Lisp is
extremely important, and it's immensely useful to be able to discern the
two without having to inspect the definitions (and then remember it).

> Not only has that ship has sailed, but different modes are free to
> highlight whatever they consider significant, at different font lock
> levels. (Granted, `dash.el` does not currently come with an optional
> minor mode to allow toggling this behaviour, but it could, as part of
> my suggestion above.)

"that ship has sailed"? Heh. Well, I hope not. It's never too late to
make your package a better community member. One learns new things every
day.

(And again, we're not talking about "different modes" here. You're not
defining any major mode.)

As for toggling the behaviour, I think it's not even on by default any
more. Really, this report was meant more as a friendly nudge; I'm not
affected by the problem in any way.

>> On another note, the whole dash-enable-fontlock thing seems obsolete,
>> as recent Emacsen do the proper fontification automatically.
>
> Proper fontification of what?

Proper fontification of the new emacs-lisp-mode identifiers defined by
your package.

**Comment by magnars** [comment]
Your suggestion sounds good, Basil. Thanks! Pull request welcome. :)

**Comment by basil-conto** [comment]
>>> I don't think this is relevant.

>> Why not?

> Because we're not talking about a new major mode where you define your own font locking, we're talking about emacs-lisp-mode and your library being (or not) a good Emacs citizen, so to speak.

Does my suggestion not allow Dash to be a better Emacs citizen?

>>> You simply don't font lock elisp functions with font-lock-keyword-face, ever (only macros and special forms).

>> Can you please point me to some documentation that contains this edict?

> I can't. I'm not aware of the "edict" being written anywhere.

Then there's a good chance that this isn't a hard and fast rule, and my personal experience agrees with this conclusion.

If you would like to suggest documenting such a convention, I suggest you either submit a bug report via the `report-emacs-bug` command, or write to `emacs-devel@gnu.org`.

> I guess most people just get it. But if you still don't get it

I never said I didn't get it; in fact, I said the opposite: that I sympathise with the issue you are raising, and would like to see the default behaviour either change for the better, or be made more configurable.

> and my original explanation didn't suffice, here are a few further points: Have a look at how Emacs (core, although in about 10 years I've been using Emacs I don't remember ever seeing anyone else break this convention) does elisp font locking. Didn't it ever seem strange to you that function names are not highlighted?

No.  If I were to find anything strange, it would be that `emacs-lisp-mode` (or whichever other mode I'm using) does not let me configure this fontification.

> If not, now that I pointed that out, why do you think it is so? The difference between macros and functions in Lisp is extremely important, and it's immensely useful to be able to discern the two without having to inspect the definitions (and then remember it).

I agree, which is why I'm trying to come up with a solution which keeps both the maintainers and users like you and me happy.

> "that ship has sailed"? Heh. Well, I hope not.

The ship I'm talking about is that Dash already does this, has been doing so for a while, and the maintainers seem to like this default behaviour.

> It's never too late to make your package a better community member. One learns new things every day.

Agreed.

> (And again, we're not talking about "different modes" here. You're not defining any major mode.)

I am definitely contemplating providing a minor mode for editing "Dashful" Elisp, as it would allow cleaner toggling and configuring of things like fontification. Do you think this is a bad idea? If so, why?

> As for toggling the behaviour, I think it's not even on by default any more. Really, this report was meant more as a friendly nudge; I'm not affected by the problem in any way.

Oh, right. The fact that I call `dash-enable-font-lock` in my own config, together with the comment by @Fuco1, gave me the impression that it was enabled by default; I'm sorry about any confusion that caused. In that case there is even less to compromise on.

>> Proper fontification of what?

> Proper fontification of the new emacs-lisp-mode identifiers defined by your package.

There's still the issue of the special variables `it`, `it-index`, `acc`, and `other`, though.

**Comment by stepnem** [comment]
I'm sorry, but this is getting a bit out of hand, or, put another way,
I'm not interested in painting this particular bike shed.

This is Emacs, knock yourselves out.

(I do believe you all mean well, but I'm having too hard a time getting
my point across to be willing to continue trying. Sorry if that seems
unproductive. Thanks.)

**Comment by basil-conto** [comment]
> I'm sorry, but this is getting a bit out of hand, or, put another way, I'm not interested in painting this particular bike shed.

This isn't a bikeshed, it's a preliminary discussion on how best to solve the issue of Dash fontifying everything and the kitchen sink. So far I have heard no arguments against my initial thoughts.

> (I do believe you all mean well, but I'm having too hard a time getting my point across to be willing to continue trying. Sorry if that seems unproductive. Thanks.)

I'm sorry if I frustrated you with my initial confusion. FWIW, I believe I have understood and agree with your point, and am merely brainstorming how to solve the issue in a backward-compatible way.

**Comment by basil-conto** [comment]
@stepnem 

> As a rule, only macros and special forms are highlighted as keywords in Emacs Lisp mode. dash.el breaks this convention by highlighting everything, including functions. Please don't do this, it's confusing (it's useful to distinguish functions from macros for obvious reasons, notably evaluation of arguments and usability in higher order functions; I found it surprising that such a widely used library aimed at functional programming style should commit this error in the first place).

I have now fixed this in #311; please review.

> On another note, the whole dash-enable-fontlock thing seems obsolete, as recent Emacsen do the proper fontification automatically.

Indeed, #311 now only registers macro names in Emacs 24, which was the last Emacs version to have static macro call fontification. Emacs 25 and later detect macro calls dynamically.

---

> Perhaps `dash-enable-fontlock` could be extended to allow for multiple levels of font lock

This turned out to be infeasible, as font lock levels only apply to major, not minor, modes.

> The question is where can we strike a balance/compromise between the current behaviour (that the maintainers seem to want to keep) and a less intrusive default that is more consistent with `emacs-lisp-mode`

I originally misunderstood the maintainers' comments, and now strongly hold the same opinion as @stepnem that Dash has no place fontifying function calls in Emacs Lisp. #311 removes this behaviour, keeping only the fontification of special anaphoric Dash variables and, in older Emacs versions, Dash macro calls.

> I'll also see if I can limit the special variable highlighting to the bodies passed to Dash macros, but no promises. ;)

I still believe this is possible, but I did not attempt to implement this just yet.

**Comment by alphapapa** [comment]
FYI, there is a package for highlighting function calls, which I find particularly useful.  ;)  https://github.com/alphapapa/highlight-function-calls

**Comment by basil-conto** [comment]
> FYI, there is a package for highlighting function calls, which I find particularly useful. ;) https://github.com/alphapapa/highlight-function-calls

Thanks @alphapapa, I was not aware of it and can see its utility. However it is not the place of Dash to selectively perform any such highlighting and thus diverge from `emacs-lisp-mode`.

**Comment by alphapapa** [comment]
Yes, I agree.  It belongs in a separate package.  ;)

**Comment by Fuco1** [comment]
It was a separate minor mode, or at least could be made into one.  I am quite used at the dash functions being fontified now and would like to keep an option for users to enable that behaviour... even if it is not "proper" with respect to Emacs (which really is nowhere codified and also dash predates the changes where the macro fontification was introduced).

If we turn it into a separate package or minor mode I don't care.  Or at least some gist with copy-pastable code which I can put in my init file.

**Comment by basil-conto** [comment]
> I am quite used at the dash functions being fontified now and would like to keep an option for users to enable that behaviour

> If we turn it into a separate package or minor mode I don't care.

Okay, I'll try to bring back function call fontification by the end of the week.

In the meantime I'd be grateful if someone could review #309 (which is a blocker for this) and the rest of #311.

**Comment by alphapapa** [comment]
@Fuco1 If I understand correctly what you're wanting, it would be simple to modify `highlight-function-calls` to highlight certain symbols differently.  It already does that for certain ones, so it would be simple to add some flexible lists of symbols and faces, so you could choose to e.g. highlight Dash-related symbols with a certain face.

**Comment by Fuco1** [comment]
@alphapapa Ok, I'll look into that package.  @basil-conto Don't implement this in the meantime, if we have a better solution with the other package that indeed makes sense as it is already focused on this.

Also using the built-in hilight might be a viable option.

**Comment by basil-conto** [comment]
> Don't implement this in the meantime, if we have a better solution with the other package that indeed makes sense as it is already focused on this.

Okay, I'll hold off.

> Also using the built-in hilight might be a viable option.

Which built-in highlighting? You mean `hi-lock.el`?

**Comment by Fuco1** [comment]
@basil-conto There is a bunch of functions like `highlight-regexp` and friends which are built-in.  I could probably just use that and a hook in my config.

**Comment by basil-conto** [comment]
> There is a bunch of functions like `highlight-regexp` and friends which are built-in.

Yes, those are in the `hi-lock.el` library that I referenced.
