### ISSUE TITLE
add --accumulate

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [magnars/dash.el#304]
Often I find I want to transform a sequence to another sequence, but I also want some side-effect to happen at the same time. Since there is a side-effect involve I should use `-each` or `--each`.

So I end up having to do this.

```elisp
(let (result number-count)
  (--each somelist
    (when (numberp) (incf number-count)) ; side-effect
    (push (dosomethingto it) result))
  (nreverse result))
```
I think having to let-bind a variable to get the result occurs so often, that we should have some abstraction to just return accumulated values like this automatically. 

Despite it's syntax, I think `cl-loop` did well in at least recognizing how often this kind of let-binding occurs and trying to abstract it.

```elisp
(cl-loop for i in somelist
         do (when (numberp i) (incf number-count))
         collect (dosomethingto it))
```
I've wished I could just do something similar with dash:

```elisp
(--accumulate somelist #'list
  (when (numberp it) (incf number-count))
  (dosomethingto it))
```
signature: (--accumulate list fn &rest forms)

The return value of accumulate is `fn` applied to the collection of values retuned by forms for each iteration.

**Comment by Fuco1** [comment]
Would `-doto` help here?

**Comment by Luis-Henriquez-Perez** [comment]
Could you provide an example of how it would be used here? I'm not understanding.

**Comment by Fuco1** [comment]
I don't know either, but it looks similar :D Sorry, I just remembered it existed and might be helpful.

If it's not obvious then probably it does something else.

**Comment by Luis-Henriquez-Perez** [comment]
😆  I spent while thinking about how it `-doto` fit in and even looked up examples in clojure. Thanks for mentioning it though. I could definitely be missing something though. I realize I might be thinking of the typical way of doing it and missing the functional way.

One of the things I love most about `dash` is that it allowed me to pretty much replace every use case I had of `cl-loop` with more readable and more concise code. I dislike the syntax of `cl-loop`. There are only very few cases I still use `cl-loop` and I strive to eliminate even those.

I'll investigate how this kind of thing is done in clojure.

**Comment by Fuco1** [comment]
I re-read your top post

> The return value of accumulate is fn applied to the collection of values retuned by forms for each iteration.

So how is this different from `-map`?

**Comment by Luis-Henriquez-Perez** [comment]
Its the same as map. I didn't use map because it had a side effect and I thought map was strictly for cases with no side effects.

**Comment by Fuco1** [comment]
Well, elisp doesn't care.  I think I would prefer one function over two which do the same except differ in name.

**Comment by magnars** [comment]
That would be the case if -map was lazy, but that’s the one feature dash
doesn’t have at this point. ^^

ons. 5. jun. 2019 kl. 13:57 skrev Mokey Mokey <notifications@github.com>:

**Comment by Luis-Henriquez-Perez** [comment]
I agree that one function definitely better.
 
Perhaps I'll just alias '-map' to '-accumulate' and only use the latter name when I have side effects going on.

**Comment by basil-conto** [comment]
> I realize I might be thinking of the typical way of doing it and missing the functional way.

The "functional way" comes with the following rules of thumb:
1. For mapping values in one list to values in another list 1-to-1, use `-map`.
2. For extracting or transforming a subset of a list, use `-filter`, `-remove`, or `-keep`.
3. For any other kind of accumulation of a value across a list, there's `-reduce`.

For `-map`ping a function across a list and simultaneously accumulating a separate value, Haskell provides `mapAccumL` and `mapAccumR`, but in Elisp these would be only slightly different and more convenient than using `-reduce` or `-map`. In fact, even (1) and (2) above are just common patterns that can be implemented in terms of `-reduce`.

So for the most functional style in Elisp, you could currently do something like the following:

```el
(let ((res (-reduce-from (-lambda ((count . list) it)
                           (when (numberp it) (cl-incf count))
                           `(,count ,(dosomethingto it) ,@list))
                         '(0)
                         '(0 1 nil 2 3 nil 4 5))))
  (setcdr res (nreverse (cdr res)))
  res) ;; => (count . result)
```

(Actually, an even more functional style would `-map` `dosomethingto` over the list, and call `-count` on it separately.)

You could define something like `mapAccumL` in Dash:

```el
(defmacro --map-accum (form initial-value list)
  (let ((l (make-symbol "list")))
    `(let* ((acc ,initial-value)
            (,l (--map ,form ,list)))
       (cons acc ,l))))
```

but as you can see it's not that different to using `-reduce` directly:

```el
(--map-accum (progn (when (numberp it)
                      (cl-incf acc))
                    (dosomethingto it))
             0 '(0 1 nil 2 3 nil 4 5)) ;; => (count . result)
```

and there's really no reason to pretend that Elisp is so purely functional, so I encourage you to write the following clearer, more idiomatic, and more efficient code instead:

```el
(let ((count 0))
  (mapcar (lambda (it)
            (when (numberp it) (cl-incf count))
            (dosomethingto it))
          '(0 1 nil 2 3 nil 4 5)))
```
