### ISSUE TITLE
adding orElse for partial functions

### ISSUE THREAD

**Issue by ag91** [magnars/dash.el#306]
Hi there, thanks for the library: it has a lot of goodies!
I was working on some functionality I want to add to Emacs and I found out I needed an orElse (https://stackoverflow.com/questions/38863103/what-is-correct-way-to-use-operator-orelse-in-scala):
It basically recover on elisp functions that return `nil` for some inputs by running another elisp function on the same input. This is what I came with:

``` elisp
   (defun a (i) (if (< i 0) "first" nil))
   (defun b (i) (if (> i 0) "second" nil))
   (defun c (i) "third")
   (defun or-else (f g) `(lambda (i) (let ((x (,f i))) (or x (,g i)))))
   (funcall (or-else 'a 'b) -10)
   (funcall (or-else 'a (or-else 'b 'c)) 0)
```
Can this be an addition to your collection of useful functions? Or maybe this is already there and I did not see it?

Thanks again!

**Comment by Fuco1** [comment]
The function seems useful and can be implemented directly as closure without using the backtick macro.  We could also make it take arbitrary number of functions not just two.

**Comment by basil-conto** [comment]
This sounds like a more useful extension of `-orfn`:

```el
(defun -orfn (&rest preds)
  "Return a function which acts like `or' on the results of PREDS.
The returned function takes a variable number of ARGS.  When
called, it applies each n-ary function in PREDS to ARGS in turn
until one of them returns non-nil, then returns that value.  The
remaining PREDS are not called at all.  If all PREDS return nil,
the returned function also returns nil."
  (lambda (&rest args)
    (--some (apply it args) preds)))
```

If this is a welcome extension, I will submit a PR which makes other unary `dash-functional` definitions n-ary.

**Comment by Fuco1** [comment]
I would prefer to keep the original `-orfn` definition since some people might rely on it returning `t` or `nil`.  We can call this `-somefn` perhaps?

**Comment by magnars** [comment]
Agreed. Let’s not break people’s code. A new name is the way to go.

lør. 17. aug. 2019 kl. 22:53 skrev Matus Goljer <notifications@github.com>:

**Comment by basil-conto** [comment]
Of course I will ultimately heed the maintainers' wishes, but here are some arguments for extending `-orfn` instead of introducing yet another variation of an existing model, which I am personally against:

* The documentation of `-orfn` does not currently say that it returns `t`, but rather non-`nil`. In other words, the fact that it returns `t` is an implementation detail, and client code that depends on this is inherently brittle. There's no need to restrict `dash` because of this.
* `or`, which `-orfn` mirrors, returns either `nil` or one of its non-`nil` arguments, not `t` specifically. As such, `-orfn` is currently not only less useful than it could be, but also inconsistent with its namesake.
* Idiomatic Elisp code rarely checks for `t` specifically; this is only done when the value of a variable or function is documented as being a member of a specific set of values, which is not the case with `or` or `-orfn`.

Given the above, I think both that it is fine to extend `-orfn` in the proposed way, and that the risk of unwarranted breakage is negligible.

WDYT?

**Comment by Fuco1** [comment]
You might acually have a point.  Though it does say `a -> Bool` in the docstring, which means `t` or `nil`.  Granted it's haskell notation not familiar to everyone.

I think you might have a case after all.

**Comment by magnars** [comment]
Seems reasonable.

søn. 18. aug. 2019 kl. 17:01 skrev Basil L. Contovounesios <
notifications@github.com>:

**Comment by ag91** [comment]
That sounds cool! It seems I will be able to use this function from dash.el soon enough :)

By the way, @Fuco1 is this what you mean by having that function without using the backtick macro?

``` elisp
(defun or-else (&rest fs)
     "Compose partial functions FS until one of them produces a result or there are no more FS available."
     (lexical-let ((my-fs fs))
       (lambda (i)
        (reduce
         (lambda (acc f) (or acc (funcall f i)))
         my-fs
         :initial-value nil))))
```
I would be really eager to see better elisp code, if you have time and patience :)

**Comment by basil-conto** [comment]
> is this what you mean by having that function without using the backtick macro?

Close enough, but without using `lexical-let` and `reduce` from the obsolete `cl` library (Dash also avoids using the more modern `cl-lib` library).

In particular, Dash now assumes Emacs > 24 (and thus `lexical-binding`), so there's no need for `lexical-let` at all, and Dash provides its own `-reduce` et al. functions.

> I would be really eager to see better elisp code, if you have time and patience :)

See my first comment in this thread for the simplest implementation suggested so far: https://github.com/magnars/dash.el/issues/306#issuecomment-522259977

> It seems I will be able to use this function from dash.el soon enough :)

I am on holiday until 25th August, after which I

**Comment by yyoncho** [comment]
> Given the above, I think both that it is fine to extend -orfn in the proposed way

IMO the same change should be applied to `-andfn`

**Comment by Fuco1** [comment]
Agreed, we should do the same to `-andfn` to keep then logically consistent.  Thanks for taking care of this @basil-conto !

**Comment by basil-conto** [comment]
> IMO the same change should be applied to `-andfn`

Agreed, which is why I originally said:

> If this is a welcome extension, I will submit a PR which makes other unary `dash-functional` definitions n-ary.

**Comment by basil-conto** [comment]
I have started some initial work in PR #308.

**Comment by basil-conto** [comment]
PR #308 has now been merged.
