### ISSUE TITLE
-inits destroys inputs

### ISSUE THREAD

**Issue by SwiftLawnGnome** [magnars/dash.el#312]
The list passed to `-inits` is destroyed by the `nreverse`. Here's a version that wouldn't (and is lower time complexity, I think.)

```elisp
(defun -inits (list)
  "Return all prefixes of LIST."
  (let ((acc nil)
        (ret (list nil)))
    (--each list
      (!cons it acc)
      (!cons (reverse acc) ret))
    (nreverse ret)))
```

**Comment by basil-conto** [comment]
> The list passed to `-inits` is destroyed by the `nreverse`.

Right you are!

> Here's a version that wouldn't (and is lower time complexity, I think.)

Thanks, I'll benchmark a few different possible implementations and get back to you before the end of the week. In the meantime feel free to submit a PR.

[BTW, @magnars @Fuco1: does Dash require legally significant contributors (i.e. of more than ~15 LoC) to assign their copyright to the FSF?]

**Comment by SwiftLawnGnome** [comment]
Good question. I just filled out the questionnaire and sent it to assign@gnu.org, so I should get the necessary forms soon.

**Comment by Fuco1** [comment]
@basil-conto Yes we do since the #160

**Comment by Fuco1** [comment]
A simpler patch would be

```diff
diff --git a/dash.el b/dash.el
index 587c074..98990e8 100644
--- a/dash.el
+++ b/dash.el
@@ -2329,7 +2329,7 @@ or with `-compare-fn' if that's non-nil."
 
 (defun -inits (list)
   "Return all prefixes of LIST."
-  (nreverse (-map 'reverse (-tails (nreverse list)))))
+  (nreverse (-map 'reverse (-tails (reverse list)))))
 
 (defun -tails (list)
   "Return all suffixes of LIST"
```

**Comment by basil-conto** [comment]
> A simpler patch would be

[...]

Indeed that is the simplest bugfix, but see #313 for discussion of some faster implementations that do not suffer from the original bug.
