### ISSUE TITLE
would you like let-while?

### ISSUE THREAD

**Issue by nicferrier** [magnars/dash.el#32]
I came up with this the other day:

```
(defmacro* let-while ((var expression) &rest body)
  "A simple binding loop.

VAR is bound to EXPRESSION repeatedly until `nil'.

BODY is evaluated each time."
  (declare
   (debug (sexp sexp &rest form))
   (indent 1))
  (let ((expression-proc (make-symbol "exprp")))
    `(let ((,expression-proc (lambda () ,expression)))
       (let ((,var (funcall ,expression-proc)))
         (while ,var
           (progn ,@body)
           (setq ,var (funcall ,expression-proc)))))))

(defun let-while-test ()
  (catch :io
    (let ((lines '("line 1" "line 2")))
      (flet ((get-line ()
               (or
                (pop lines)
                (throw :io :eof))))
        (let-while (line (get-line))
          (message "the line is: %s" line))))))
```

It's very useful for using with iterators. I'm not sure you want to go down the iterator route but this might still be useful.

**Comment by alphapapa** [comment]
Just wanted to say thanks to Nic for sharing this.  I was surprised that there isn't such a macro in a package somewhere.  I think it would be very useful.  For example, building an `re-search-forward` type function that operates on larger chunks of text, you could do something like:

```el
(-let-while (entry (get-next-entry pattern))
              (message "ENTRY: %s" entry))
```

Of course, I'm still an elisp noob, so maybe there's a better way...?  :)

**Comment by Fuco1** [comment]
There's `do` macro which is similar but incredibly difficult to use (I can't read it at all).  Given all the `-let` variants in dash I don't think this is totally off topic... maybe all those could be split away somewhere?  I think this would be a  nice idea to process event-like stuff, consider the `while (event = poll()) {...}` C-like idiom.

**Comment by magnars** [comment]
Yeah, I like it as well.
tor. 31. mar. 2016 kl. 18.35 skrev Matus Goljer <notifications@github.com>:

**Comment by alphapapa** [comment]
@Fuco1 Yeah, for example, this `cl-loop` loop could be replaced with this `-let-while`:

```el
(cl-loop for ret = (get-next-entry)
         while ret
         do (message "%s" ret))

(-let-while (entry (get-next-entry))
            (message "%s" ret))
```

And for a `let*`-style example:

```el
(setq example-times 0)
(defun example ()
  (when (< example-times 5)
    (incf example-times)
    `("Heading" . ,(float-time))))

(cl-loop for ret = (example)
         while ret
         for heading = (car ret)
         do (message "%s" heading))

(-let-while* ((ret (example))
              (heading (car ret)))
             (message "%s" heading))
```

**Comment by Fuco1** [comment]
What should it do with multiple bindings? Require that all are non-nil?

It should be rather simple to wrap `-let-when` with while somehow.

**Comment by alphapapa** [comment]
> What should it do with multiple bindings? Require that all are non-nil?

That seems useful to me.  It would let you destructure and test what the first binding returns, like this `cl-loop` but less verbosely:

```el
  (cl-loop for ret = (example)
           while ret
           for heading = (car ret)
           while heading
           do (message "%s" heading))
  
  (-let-while* ((ret (example))
                (heading (car ret)))
               (message "%s" heading))
```
