### ISSUE TITLE
Register Dash Info manual with info-look.el for C-h S

### ISSUE THREAD

**Issue by emacs18** [magnars/dash.el#326]
Melpa recipe for dash is the following:

```
(dash :fetcher github :repo "magnars/dash.el" :files ("dash.el"))
```

I think this should be modified to include dash.texi, i.e., 

```
(dash :fetcher github :repo "magnars/dash.el" :files ("dash.el" "dash.texi"))
```
This change will include dash.info documentation file when the package is built.

Do you agree that this is a good change to make?
If you do, then I'll submit a pull request at https://github.com/melpa/melpa

**Comment by Fuco1** [comment]
We build the info file ourselves and keep it in the repository, so that should probably be distributed instead of the .texi source.  What would be the use-case of distributing the texi file instead?

**Comment by emacs18** [comment]
Adding "dash.texi" as I have suggested simply tells package-build code that when this package is built, that is should generated info file from the texinfo file.  The net result is that dash package will include dash.info, not dash.texi.

I don't know whether you can add "dash.info" rather than "dash.texi".
Among the packages that I use such as bbdb, the melpa recipes seems to specify
the texinfo files rather than info files.

**Comment by Fuco1** [comment]
I'm no expert on this, if you think this is a useful change I have no objection to making a PR to melpa to update the recipy.  Would you like to do that?

**Comment by emacs18** [comment]
If you could submit a PR to package-build proejct, that would be best since you are the author.  I don't mind submitting PR myself, but package-build folks may come back to you anyways to get your feedback.

**Comment by Fuco1** [comment]
What is package-build?  Do you mean melpa?  They are usually OK with other people updating the requests, I'll give you a :+1: in the pull request, no problem.

**Comment by emacs18** [comment]
I submitted
https://github.com/melpa/melpa/pull/6576

**Comment by emacs18** [comment]
Once dash.info is installed, then it would be helpful if we integrate it
into info-lookup.  If it is integrated, then I can hit C-h S while
cursor is over say -map.  That will bring up info browser with dash.info
loaded and showing exactly the right line that documents -map.

I'm not familiar with modern info-lookup.el, so I don't know how to
customize it to integrate dash.info.  So I just modified emacs itself to
add one line as shown below.


```
diff --git a/lisp/info-look.el b/lisp/info-look.el
index 8a484bbed1..2a8551cc37 100644
--- a/lisp/info-look.el
+++ b/lisp/info-look.el
@@ -933,6 +933,7 @@ Return nil if there is nothing appropriate in the buffer near point."
              ;; for things that should go to Function: etc, and those latter
              ;; are much more important.  Perhaps this could change if some
              ;; sort of fallback match scheme existed.
+             ("(dash)Index"           nil "^ -+ .*: " "\\( \\|$\\)")
              ("(elisp)Index"          nil "^ -+ .*: " "\\( \\|$\\)")
              ("(cl)Function Index"    nil "^ -+ .*: " "\\( \\|$\\)")
              ("(cl)Variable Index"    nil "^ -+ .*: " "\\( \\|$\\)")))
```

Of course we cannot expect folks to edit emacs source code and rebuild
emacs to customize one variable, i.e., info-lookup-alist. I'm sure
someone more familiar with info-lookup could find a better way to
customize info-lookup-alist to add dash to emacs-lisp-mode.

**Comment by Fuco1** [comment]
The package itself should probably on load register the line in the `info-lookup-alist`.

That seems to be done through the `info-lookup-maybe-add-help` function.

**Comment by emacs18** [comment]
Yes that is why my previous patch modified info-lookup-maybe-add-help call for emacs-lisp-mode to add dash manual.  Unfortunately this cannot be called multiple times to append additional entries.

Something like the following seems to work.
However this is very ugly.  There has got to be a better way to do this.

```elisp
(require 'info-look)

(let ((doc-spec (info-lookup->doc-spec 'symbol 'emacs-lisp-mode))
      (new-entry '("(dash)Index" nil "['`‘]" "['’]")))
  (setcdr doc-spec (cons new-entry (cdr doc-spec))))
```

**Comment by basil-conto** [comment]
> There has got to be a better way to do this.

The only other way I can see is to do what Tramp does, namely create a pseudo `dash-info-lookup-mode` and add it as one of the "other modes" of `emacs-lisp-mode`; see [`lisp/net/tramp-integration.el`](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/net/tramp-integration.el#n214).

But that still involves modifying existing entries, so I don't see it as being much better.
