### ISSUE TITLE
replace package dependency cl by cl-lib?

### ISSUE THREAD

**Issue by harmeling** [magnars/dash.el#335]
in dash.el:
OLD: (require 'cl)
NEW: (require 'cl-lib)
this avoid a warning at startup that package cl is deprecated

**Comment by basil-conto** [comment]
Please state your <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd> and the precise steps that you are taking that give rise to a warning.

I do not get a warning when either byte-compiling `dash.el`, loading `dash.el`, or loading `dash.elc` on any of the following Emacs versions: 24.5.1, 25.3.1, 26.3, 27.0.91, 28.0.50.

Note that `dash.el` currently loads `cl` *only* during byte-compilation, which is correct and supported use of `cl`, and only for compatibility with Emacs versions older than 24.3 (although now that I look at it again the compatibility shim isn't entirely correct).

**Comment by harmeling** [comment]
Ok!  I checked again (Emacs 28.0.50) and didn't get a warning if dash.el is the only library that contains the "require 'cl" among the .el files in .emacs.d/elpa
So no action required.  Sorry for the confusion.

**Comment by basil-conto** [comment]
No worries, and thanks for confirming! It's hard testing this across many Emacs versions.
