### ISSUE TITLE
`dash` breaks Mac OS emacs on 27.1.

### ISSUE THREAD

**Issue by sstepashka** [magnars/dash.el#343]
Hi,

I have installed newest version of emacs from https://emacsformacosx.com and got an issue relate to wrong type argument when I open a C++ file. Here's a trace:
```
Debugger entered--Lisp error: (wrong-type-argument stringp (require . info))
  string-match("\\(\\`\\|/\\)elec-pair\\(\\.elc\\|\\.el\\|\\.so\\)?\\(\\.gz\\)?\\..." (require . info))
  load-history-filename-element("\\(\\`\\|/\\)elec-pair\\(\\.elc\\|\\.el\\|\\.so\\)?\\(\\.gz\\)?\\...")
  eval-after-load("elec-pair" #f(compiled-function () #<bytecode 0x1ff627d0cac1>))
  c-initialize-cc-mode(t)
  c++-mode()
  c-or-c++-mode()
  set-auto-mode-0(c-or-c++-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer hello.h> "~/Desktop/hello.h" nil nil "~/Desktop/hello.h" (50234033 16777220))
  find-file-noselect("/Users/kuragin/Desktop/hello.h" nil nil nil)
  find-file("/Users/kuragin/Desktop/hello.h")
  helm-find-file-or-marked("/Users/kuragin/Desktop/hello.h")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal(helm-source-find-files "/Users/kuragin/" "Find files or url: " nil nil "*helm find files*" nil nil nil)
  apply(helm-internal (helm-source-find-files "/Users/kuragin/" "Find files or url: " nil nil "*helm find files*" nil nil nil))
  helm(helm-source-find-files "/Users/kuragin/" "Find files or url: " nil nil "*helm find files*" nil nil nil)
  apply(helm (helm-source-find-files "/Users/kuragin/" "Find files or url: " nil nil "*helm find files*" nil nil nil))
  helm(:sources helm-source-find-files :input "/Users/kuragin/" :case-fold-search t :preselect nil :ff-transformer-show-only-basename t :default nil :prompt "Find files or url: " :buffer "*helm find files*")
  helm-find-files-1("/Users/kuragin/" nil)
  helm-find-files(nil)
  funcall-interactively(helm-find-files nil)
  call-interactively(helm-find-files nil nil)
  command-execute(helm-find-files)
```

The error doesn't appear if I removed `dash` and appear again again when I install it. The only additional package I have is `helm`. Even if I removed helm, and have only `dash` installed, the error appears. But,

If I opened a file by emacs from terminal, I don't see the issue:
```shell
$ emacs ~/Desktop/hello.h # no issue
```
```shell
$ emacs $ then use C-f to open the same file.
```

I'm pretty sure it's not related directly to the package and probably might be cause by new initialization separation... or some other change in emacs... like autoloading.

**Comment by sstepashka** [comment]
Also, when I'm installing the package I se an error: "End of file during parsing"... That might be related, but I don't know how to figure out the root cause of that...

**Comment by sstepashka** [comment]
Seems like it somehow related to the generated `dir` file:

```shell
% cat dash-20200803.1520/dir                     -- INSERT --
This is the file .../info/dir, which contains the
topmost node of the Info hierarchy, called (dir)Top.
The first time you invoke Info you start off looking at this node.

File: dir,	Node: Top	This is the top of the INFO tree

  This (the Directory node) gives a menu of major topics.
  Typing "q" exits, "H" lists all Info commands, "d" returns here,
  "h" gives a primer for first-timers,
  "mEmacs<Return>" visits the Emacs manual, etc.

  In Emacs, you can click mouse button 2 on a menu item or cross reference
  to select it.

* Menu:

Emacs
* Dash: (dash.info).            A modern list library for GNU Emacs
```

When I delete that file, everything start to work normally...

**Comment by sstepashka** [comment]
Seems like the problem is within emacs from https://emacsformacosx.com, I do not have such issue with emacs-plus from homebrew.

**Comment by caldwell** [comment]
Can you try with the new build? https://emacsformacosx.com/emacs-builds/Emacs-27.1-1-universal.dmg

There was an issue with the portable undumper files not being included correctly that has symptoms very similar to what you are seeing. It should be fixed in the 27.1-1 build.

**Comment by basil-conto** [comment]
Looks like other packages that install an ELPA `dir` file also saw this issue: abo-abo/swiper#2659.

**Comment by sstepashka** [comment]
@caldwell Seems like, it works. Thank you very much for the fix! Could you confirm that pretest build had the same issue?

**Comment by caldwell** [comment]
Yes, and all the portable undumped nightlies, too (not sure how long that's been on master, but quite a while I guess).

**Comment by basil-conto** [comment]
Thanks for confirming everyone, I'm therefore closing this issue.
