### ISSUE TITLE
Please upgrade version in GNU ELPA

### ISSUE THREAD

**Issue by skangas** [magnars/dash.el#344]
Could you please look into upgrading the version in GNU ELPA? The version listed is 2.12.0.

http://elpa.gnu.org/packages/dash.html

**Comment by basil-conto** [comment]
Yes, I'll be able to look into this towards the end of this month. Unfortunately quite a few changes were merged without CA, so I need to catch up with that first.

**Comment by skangas** [comment]
Thanks!

**Comment by basil-conto** [comment]
FYI I'm tracking the progress of this release at https://github.com/magnars/dash.el/projects/1.

**Comment by basil-conto** [comment]
@yyoncho Your changes in #277 and #282 are the only ones for which we need a copyright assignment in order to be able to release Dash 2.18.0.

In #336, you said 5 months ago that you would try to finish the CA process soon.  Is there any update on that?  I would be very grateful if you could look into completing the assignment process soon.

TIA.

**Comment by yyoncho** [comment]
@basil-conto I will try to finish it this week.

**Comment by basil-conto** [comment]
Thanks!

**Comment by basil-conto** [comment]
What's the status on this @yyoncho? If you're waiting more than a week or two for a response from the copyright clerk, feel free to ping them.

**Comment by yyoncho** [comment]
@basil-conto I sent the last(?) part today.

**Comment by basil-conto** [comment]
@yyoncho Great, thanks! Let us know when they get back to you to confirm.

**Comment by yyoncho** [comment]
@basil-conto it is done.

**Comment by basil-conto** [comment]
Fingers crossed Dash 2.18.0 is coming to an ELPA near you:

https://git.savannah.gnu.org/cgit/emacs/elpa.git/commit/?id=5496db67039ff755f10b44714e97ef7d373c0122

**Comment by basil-conto** [comment]
Seems to have gone smoothly, and now auto-syncs just like MELPA Stable: https://elpa.gnu.org/packages/dash.html

**Comment by magnars** [comment]
Good job! 👏😊

man. 15. feb. 2021 kl. 23:43 skrev Basil L. Contovounesios <
notifications@github.com>:

**Comment by basil-conto** [comment]
Thanks, and thanks to everyone who helped push this past the line!

**Comment by skangas** [comment]
Thanks!
