### ISSUE TITLE
a combination of -take and -take-while

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [magnars/dash.el#345]
An idea for a combination of `-take` and `-take-while` I thought might be useful.

```elisp
(-take-n-while 2 #'keywordp '(:a 2 :b 3 :b 4 "some" other 4 stuff))
;; => '(:a 2 :b 3 :b 4)


(-drop-n-while 2 #'keywordp '(:a 2 :b 3 :b 4 "some" other 4 stuff))
;; => '("some" other 4 stuff)
```

**Comment by basil-conto** [comment]
Sorry, I don't understand the intended semantics of the first argument in your examples. What does the `2` mean, and how does it behave in conjunction with `keywordp`?

**Comment by Fuco1** [comment]
I would expect this to take first `n` items satisfying the predicate, i.e. 

    -take-n-while n predicate = -take n . -filter predicate

**Comment by basil-conto** [comment]
Yes, but that is not what is shown in the examples, AFAICT.

**Comment by Fuco1** [comment]
You're right, that's what I would imagine the function to do, but actually from the name it makes more sense to continue while the predicate was satisfied `n` times.  Which seems like what the example should do except it counts `n+1`.  I guess.

**Comment by Luis-Henriquez-1** [comment]
I envisioned that ```take-n-while``` would be act like this form.

It takes N items from the list when the first element of the list satisfies its predicate.

```elisp
(let ((list '(:a 1 :b 2 :c 3 "some" 'random))
      (result nil)
      (pred #'keywordp)
      (n 2))
  (while (funcall pred (car list))
    (setq result (append result (-take n list)))
    (setq list (-drop n list)))
  result)
;; => '(:a 1 :b 2 :c 3)
```

**Comment by basil-conto** [comment]
> It takes N items from the list when the first element of the list satisfies its predicate.

Then the `while` in the function's name is misleading, because it suggests that the action will be taken as long as the predicate is true.

**Comment by basil-conto** [comment]
>> It takes N items from the list when the first element of the list satisfies its predicate.

> Then the `while` in the function's name is misleading, because it suggests that the action will be taken as long as the predicate is true.

Sorry, I was wrong. The function's purpose is to continue taking `N` items so long as the list's head satisfies the predicate.

Could you provide a sample use case for such a function, to justify its addition to Dash? As opposed to implementing it yourself in your application code, e.g. with the following more efficient implementation:

```el
(defun my-take-n-while (n pred list)
  (let ((tail list) (count 0))
    (while (and tail (funcall pred (car tail)))
      (setq count (1+ count) tail (nthcdr n tail)))
    (-take (* count n) list)))
```

**Comment by alphapapa** [comment]
FYI, using `cl-loop` is about 2.6 times faster than even that:
```el
(let ((args '(:a 2 :b 3 :c 4 "some" other 4 stuff)))
  (list (cl-loop for arg in args by #'cddr
                 while (keywordp arg)
                 collect (pop args)
                 collect (pop args))
        args))
;;=> ((:a 2 :b 3 :c 4) ("some" other 4 stuff))
```

**Comment by basil-conto** [comment]
> FYI, using cl-loop is about 2.6 times faster than even that:

That's not doing the same thing: it's not generalised for arbitrary `N` or `PRED`, and it doesn't return a flat prefix/suffix of the input list.

**Comment by alphapapa** [comment]
> everything `cl-loop` can do, Elisp can, too ;)

`cl-loop` is Elisp ;)

**Comment by basil-conto** [comment]
> It's just FYI as to the performance difference.

The performance difference between what? Could you please demonstrate it?

**Comment by Fuco1** [comment]
I think this function is interesting but I struggle to find some use cases for it.  Seems like it could be defined in terms of partitions and filters:

```
(->> (list :a 1 :b 2 :c 3 "some" 'other :d 4)
     (-partition 2)
     (--take-while (keywordp (car it)))
     (-flatten-n 1))
```

Is this the semantics we want?

**Comment by basil-conto** [comment]
> I think this function is interesting but I struggle to find some use cases for it.

Same here. It just feels too "oddly specific" ;).

> Is this the semantics we want?

Yes, except for its performance semantics ;).

**Comment by basil-conto** [comment]
Closing this until further notice, but if anyone shows interest in and use for this again, we can always reopen.
