### ISSUE TITLE
Some aliases don't work as expected

### ISSUE THREAD

**Issue by hatlafax** [magnars/dash.el#348]
I'm new to dash. I'm working through the dash functions in order to familiarize with the concepts. With some of the aliases I found inconsitencies.

(-map-first 'evenp 'square '(1 2 3 4)) ;; => '(1 4 3 4)  as expected
(-replace-first 'evenp 'square '(1 2 3 4)) ;; => '(1 2 3 4)  not expected

Same problem happens for -map-last/-replace-last. However, -replace-where give me the expected result.

Did I spot a bug?

**Comment by basil-conto** [comment]
> With some of the aliases I found inconsitencies.

Which aliases are you referring to?

> (-replace-first 'evenp 'square '(1 2 3 4)) ;; => '(1 2 3 4) not expected

The first two arguments for `-replace-first` are list elements, not membership predicates. See its docstring:

```
-replace-first is a compiled Lisp function in `dash.el'.

(-replace-first OLD NEW LIST)

  This function does not change global state, including the match data.

Replace the first occurrence of OLD with NEW in LIST.

Elements are compared using `equal'.

See also: `-map-first'
```

So a correct example would be:

```el
(-replace-first 2 4 '(1 2 3 4)) ; => (1 4 3 4)
```

> Same problem happens for -map-last/-replace-last.

These functions are not aliases of one another either.

When a docstring says "see also", it is referring you to other related definitions that may be of interest, not listing aliases.

> Did I spot a bug?

Not as far as I can see - unless you came across some misleading documentation about aliases.

**Comment by hatlafax** [comment]
Ups, now I see ;-) Actually, I read 'alias' for the -replace-where function and oversaw the 'see also' in the -replace-first/last case. Sorry, for taking your time. I will read more carefully next time.

**Comment by basil-conto** [comment]
No bother! Thanks for confirming.
