### ISSUE TITLE
[discussion] -reduce-* performance and mapc 

### ISSUE THREAD

**Issue by yyoncho** [magnars/dash.el#350]
Is there a reason for not using `mapc` for `-reduce` implementation (and for several other functions) given the performance benefits? 

```
(defun my-reduce-from (fn initial-value list)
  (let ((result initial-value))
    (mapc (lambda (item) (setq result (funcall fn item result))) list)
    result))

(let ((range (number-sequence 1 1000)))
  (benchmark-run 1000 (-reduce-from #'+ 0 range )))
;; (0.623629283 0 0.0)

(let ((range (number-sequence 1 1000)))
  (benchmark-run 1000 (my-reduce-from #'+ 0 range )))
;; (0.101517418 0 0.0)
```

**Comment by basil-conto** [comment]
Sorry, I can't reproduce this.  Here's the benchmark I'm using:

```el
;;; bench-dash.el --- benchmark dash.el -*- lexical-binding: t -*-

;;;; Original definitions.

(defmacro !cdr (list)
  "Destructive: Set LIST to the cdr of LIST."
  `(setq ,list (cdr ,list)))

(defmacro --each (list &rest body)
  "Anaphoric form of `-each'."
  (declare (debug (form body))
           (indent 1))
  (let ((l (make-symbol "list")))
    `(let ((,l ,list)
           (it-index 0))
       (while ,l
         (let ((it (car ,l)))
           ,@body)
         (setq it-index (1+ it-index))
         (!cdr ,l)))))

(defmacro --reduce-from (form initial-value list)
  "Anaphoric form of `-reduce-from'."
  (declare (debug (form form form)))
  `(let ((acc ,initial-value))
     (--each ,list (setq acc ,form))
     acc))

(defun -reduce-from (fn initial-value list)
  "Return the result of applying FN to INITIAL-VALUE and the
first item in LIST, then applying FN to that result and the 2nd
item, etc. If LIST contains no items, return INITIAL-VALUE and
do not call FN.

In the anaphoric form `--reduce-from', the accumulated value is
exposed as symbol `acc'.

See also: `-reduce', `-reduce-r'"
  (--reduce-from (funcall fn acc it) initial-value list))

;;;; Modified without index counter.

(defmacro --each2 (list &rest body)
  "Anaphoric form of `-each'."
  (declare (debug (form body))
           (indent 1))
  (let ((l (make-symbol "list")))
    `(let ((,l ,list))
       (while ,l
         (let ((it (car ,l)))
           ,@body)
         (!cdr ,l)))))

(defmacro --reduce-from2 (form initial-value list)
  "Anaphoric form of `-reduce-from'."
  (declare (debug (form form form)))
  `(let ((acc ,initial-value))
     (--each2 ,list (setq acc ,form))
     acc))

(defun -reduce-from2 (fn initial-value list)
  "Return the result of applying FN to INITIAL-VALUE and the
first item in LIST, then applying FN to that result and the 2nd
item, etc. If LIST contains no items, return INITIAL-VALUE and
do not call FN.

In the anaphoric form `--reduce-from', the accumulated value is
exposed as symbol `acc'.

See also: `-reduce', `-reduce-r'"
  (--reduce-from (funcall fn acc it) initial-value list))

;;;; Using mapc.

(defun -reduce-mapc (fn initial-value list)
  (let ((acc initial-value))
    (mapc (lambda (it) (setq acc (funcall fn acc it))) list)
    acc))

;;;; Benchmark.

(dolist (l '(10 100 1000))
  (message "\nLength %d" l)
  (setq l (number-sequence 1 l))
  (dolist (f '(-reduce-from -reduce-from2 -reduce-mapc))
    (dotimes (_ 4)
      (garbage-collect)
      (message "%14s: %s" f (benchmark-run 1000 (funcall f #'+ 0 l))))))

;;; bench-dash.el ends here
```

This gives the following results:

```
emacs -Q -batch -f batch-byte-compile foo.el && emacs -Q -script foo.elc

Length 10
  -reduce-from: (0.011626467 0 0.0)
  -reduce-from: (0.000746728 0 0.0)
  -reduce-from: (0.0008135740000000001 0 0.0)
  -reduce-from: (0.000883806 0 0.0)
 -reduce-from2: (0.001181476 0 0.0)
 -reduce-from2: (0.00067943 0 0.0)
 -reduce-from2: (0.000712629 0 0.0)
 -reduce-from2: (0.0006864099999999999 0 0.0)
  -reduce-mapc: (0.0028062210000000002 0 0.0)
  -reduce-mapc: (0.002729473 0 0.0)
  -reduce-mapc: (0.001824725 0 0.0)
  -reduce-mapc: (0.001638479 0 0.0)

Length 100
  -reduce-from: (0.006196888 0 0.0)
  -reduce-from: (0.006208637 0 0.0)
  -reduce-from: (0.006240761 0 0.0)
  -reduce-from: (0.006250066 0 0.0)
 -reduce-from2: (0.0070019800000000005 0 0.0)
 -reduce-from2: (0.006442653 0 0.0)
 -reduce-from2: (0.0062654600000000005 0 0.0)
 -reduce-from2: (0.006571721 0 0.0)
  -reduce-mapc: (0.009890644 0 0.0)
  -reduce-mapc: (0.009329876999999999 0 0.0)
  -reduce-mapc: (0.010025759 0 0.0)
  -reduce-mapc: (0.009002431 0 0.0)

Length 1000
  -reduce-from: (0.062640756 0 0.0)
  -reduce-from: (0.06442919999999999 0 0.0)
  -reduce-from: (0.062109990999999996 0 0.0)
  -reduce-from: (0.069516336 0 0.0)
 -reduce-from2: (0.069462647 0 0.0)
 -reduce-from2: (0.061972059999999995 0 0.0)
 -reduce-from2: (0.104679834 0 0.0)
 -reduce-from2: (0.063581164 0 0.0)
  -reduce-mapc: (0.085486472 0 0.0)
  -reduce-mapc: (0.084308844 0 0.0)
  -reduce-mapc: (0.084315606 0 0.0)
  -reduce-mapc: (0.084191973 0 0.0)
```

I recently posted my full Emacs and system info at https://lists.gnu.org/r/emacs-devel/2020-12/msg00251.html.

As you can see, the current Dash functions consistently beat a `mapc` implementation by a small margin, regardless of the index counter in `--each`. I wouldn't be surprised if `mapc` and friends can beat plain list loops in Elisp, but don't forget that they iterate over the sequence more than once (the first time to calculate its length), and an extra `funcall` per item is a serious performance cost in Emacs.

**Comment by basil-conto** [comment]
I'm guessing the performance difference you're seeing is from macroexpansion of non-byte-compiled forms?

**Comment by yyoncho** [comment]
Indeed, it was an error on my side. 

> I wouldn't be surprised if mapc and friends can beat plain list loops in Elisp in certain scenarios, but don't forget that they iterate over the sequence more than once (the first time to calculate its length), and an extra funcall per item is a serious performance cost in Emacs.

Thank you for your explanation: out of curiosity, why do they have to iterate them more than once?

**Comment by basil-conto** [comment]
> out of curiosity, why do they have to iterate them more than once?

The first iteration is due to calling `length`; see the definition of `mapc`: https://git.savannah.gnu.org/cgit/emacs.git/tree/src/fns.c#n2738

The computed length is used by the subroutine `mapcar1` used by `mapconcat`, `mapcar`, `mapc`, and `mapcan`.

My guess is that computing the list length and allocating the necessary storage ahead of time was found to be more efficient in C. Perhaps there is room for improvement, e.g. in the case of `mapc` which doesn't need to allocate any storage. Patches are always welcome upstream. ;)

**Comment by basil-conto** [comment]
> Perhaps there is room for improvement, e.g. in the case of `mapc` which doesn't need to allocate any storage.

Although there is a benefit to calling `length` in the case of `mapc`, which is to check that the argument is a proper list before calling the given function on it.

**Comment by yyoncho** [comment]
> Although there is a benefit to calling `length` in the case of `mapc`, which is to check that the argument is a proper list before calling the given function on it.

There should be a more efficient way to do so.

**Comment by basil-conto** [comment]
> There should be a more efficient way to do so.

Elisp lists are singly linked, which means the only way to check if they're proper is to check if their last cdr is `nil`. Short of storing an extra pointer per list object, or reimplementing Elisp lists in terms of vectors, the only way to check the last cdr is by traversing the entire list.

**Comment by yyoncho** [comment]
FYI the issue turned out to be caused by the fact that spacemacs keeps a copy of dash in its sources and is loaded without being byte-compiled.
