### ISSUE TITLE
package is broken

### ISSUE THREAD

**Issue by asebian** [magnars/dash.el#353]
Trying to install a package from melpa that depends on dash I encountered difficulties. Finally I was able to track it down to dash.  

Problems disappear when I delete `~/.emacs.d/elpa/dash-20201223.1755`.

Here is what I get when I start emacs with the `--debug-init` option:

`Debugger entered--Lisp error: (wrong-type-argument stringp dash)
  intern(dash)
  package-desc-from-define(dash "20201223.1755" "A modern list library for Emacs" (quote nil) :commit "0517ab1ed18fd3af3c6131ca9e3a6e915036f809" :authors (("Magnar Sveen" . "magnars@gmail.com")) :maintainer ("Magnar Sveen" . "magnars@gmail.com") :keywords ("extensions" "lisp"))
  apply(package-desc-from-define (dash "20201223.1755" "A modern list library for Emacs" (quote nil) :commit "0517ab1ed18fd3af3c6131ca9e3a6e915036f809" :authors (("Magnar Sveen" . "magnars@gmail.com")) :maintainer ("Magnar Sveen" . "magnars@gmail.com") :keywords ("extensions" "lisp")))
  package-process-define-package((define-package dash "20201223.1755" "A modern list library for Emacs" (quote nil) :commit "0517ab1ed18fd3af3c6131ca9e3a6e915036f809" :authors (("Magnar Sveen" . "magnars@gmail.com")) :maintainer ("Magnar Sveen" . "magnars@gmail.com") :keywords ("extensions" "lisp")))
  package-load-descriptor("/home/geram/.emacs.d/elpa/dash-20201223.1755")
  package-load-all-descriptors()
  package-initialize()
  eval-buffer(#<buffer  *load*> nil "/home/geram/.emacs.d/init.el" nil t)  ; Reading at buffer position 1049
  load-with-code-conversion("/home/geram/.emacs.d/init.el" "/home/geram/.emacs.d/init.el" t t)
  load("/home/geram/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1e0f4d>)()
  command-line()
  normal-top-level()
`

**Comment by alphapapa** [comment]
Not a bug in this package.  See https://github.com/melpa/melpa/issues/7312
