### ISSUE TITLE
Is the watchr script still used?

### ISSUE THREAD

**Issue by basil-conto** [magnars/dash.el#357]
Commit 7b529511ddd1b463ce0eea10a82ddeaea2e207ff from 2012, which predates the first tagged release of Dash `0.1.0`, added a file `watch-tests.watchr`.

@magnars:

1. What does this file do?
2. What is it used by?
3. Is it still used?
   i. If not, can we delete it?

Thanks.

**Comment by magnars** [comment]
It was used to automatically run the tests after file changes. It can
safely be removed.

fre. 1. jan. 2021 kl. 20:38 skrev Basil L. Contovounesios <
notifications@github.com>:
