### ISSUE TITLE
I think 92393c73 has reduced polymorphism of --map, no longer works on vectors

### ISSUE THREAD

**Issue by squid-lee** [magnars/dash.el#365]
Hi,
I've hit a bug where --map is now failing.
I'm deserialising json - the emacs json API gives back vectors for some part of this.

Before 92393c73, using --map worked because it deferred to mapcar which is polymorphic over sequences.
That commit makes --map list only (afaict).

As an aside, what was wrong with making --map a thin alias of mapcar?

**Comment by basil-conto** [comment]
> I've hit a bug

That implies that `--map` was ever documented as working with vectors ;).

> I'm deserialising json - the emacs json API gives back vectors for some part of this.

FWIW, you can tell it to return lists instead. The native functions `json-parse-buffer` and `json-parse-string` accept an `:array-type` argument, and the `json.el` API uses the dynamic variable `json-array-type`.

> That commit makes --map list only (afaict).

I'm not sure what to do here. On one hand, I hate to break people's code.  On the other, the Dash API is pretty firmly list-only.  Even the argument of `--map` is called `list`. Using `mapc`/`mapcar` was an implementation detail.  Any code relying on it is arguably buggy to begin with.

> As an aside, what was wrong with making --map a thin alias of mapcar?

`--map` accepts a form as input, whereas `mapcar` accepts a function.  `--map` need only evaluate its given form once per element, but in order to use `mapcar`, it has to wrap that form in a `lambda`.  So if we use `mapcar` there is a `funcall` overhead for each element, where there otherwise wouldn't have been one:

```el
;;; bench.el --- benchmark maps  -*- lexical-binding: t -*-

(defmacro bench-old (form list)
  `(mapcar (lambda (it) (ignore it) ,form) ,list))

(defmacro bench-new (form list)
  (let ((l (make-symbol "list"))
        (r (make-symbol "res")))
    `(let ((,l ,list) ,r it)
       (ignore it)
       (while ,l
         (setq it (pop ,l))
         (push ,form ,r))
       (nreverse ,r))))

(let ((list (number-sequence 0 999))
      (reps 10000)
      (loops 3)
      result)
  (dotimes (_ loops)
    (dotimes (_ loops)
      (garbage-collect)
      (message "old: %s" (benchmark-run reps
                           (setq result (bench-old t list)))))
    (dotimes (_ loops)
      (garbage-collect)
      (message "new: %s" (benchmark-run reps
                           (setq result (bench-new t list))))))
  (ignore result))

;;; bench.el ends here
```

```
emacs -Q -batch -f batch-byte-compile bench.el && emacs -Q -script bench.elc
old: (2.462489546 200 1.944846984)
old: (2.418759833 200 1.7937253389999999)
old: (2.273961883 200 1.740805376)
new: (1.979855156 199 1.6558334840000004)
new: (1.417248008 199 1.2044808210000006)
new: (1.39184647 199 1.1842255789999996)
old: (1.5679179890000001 200 1.1927961299999996)
old: (1.569743286 200 1.194078621000001)
old: (1.5611229469999999 200 1.195425857)
new: (1.398245311 199 1.189250801)
new: (1.398561763 199 1.190328856999999)
new: (1.397545856 199 1.1895416789999995)
old: (1.551964135 200 1.1959661419999996)
old: (1.498815378 200 1.1961161629999992)
old: (1.532988673 200 1.199489358000001)
new: (1.396996419 199 1.1882569590000003)
new: (1.394444149 199 1.1866935659999989)
new: (1.394354195 199 1.186172968000001)
```

**Comment by basil-conto** [comment]
I've now reverted to using `mapcar` because it's faster than a hand-rolled loop for very large lists.

**Comment by Fuco1** [comment]
Remember that mapcar is written in C so it will always be faster in general.

There's a lot of functions which even doing unnecessary work beat elisp every time.  I know I got burned by this before (https://github.com/Fuco1/.emacs.d/commit/e854d54db331eb0447d444f117ae3ac9c159508d this led to a 10000 times speed up :D)

**Comment by basil-conto** [comment]
> Remember that mapcar is written in C so it will always be faster in general.

For some definition of generality ;). In this case the `Flength`+`Ffuncall` overhead makes `mapcar` slower than evaluating the corresponding forms in a loop for most common list sizes. It is only for degenerate lists of 100,000 items where I saw the Lisp looping overhead start to surpass that.

**Comment by basil-conto** [comment]
> There's a lot of functions which even doing unnecessary work beat elisp every time. I know I got burned by this before (Fuco1/.emacs.d@e854d54 this led to a 10000 times speed up :D)

Not surprising, since `line-number-at-pos` does a whole lot more than `(format-mode-line "%l")` ;).
