### ISSUE TITLE
cl is depreciated

### ISSUE THREAD

**Issue by wizardwatch** [magnars/dash.el#378]
https://github.com/magnars/dash.el/blob/b9286a84975874b10493f1cb4ea051c501f51273/dash.el
line 36
package cl is depreciated as of emacs 27. cl-lib should be used instead

**Comment by basil-conto** [comment]
Duplicate of #335 and #337.

**Comment by wizardwatch** [comment]
Sorry for the issue. I was going through and filing issues for everything with the line require cl, I only checked the open issues, and didn't read.

**Comment by basil-conto** [comment]
No worries! As you can see you weren't the only one to be confused by this :). Thanks for the interest.
