### ISSUE TITLE
Release 2.19.0

### ISSUE THREAD

**Issue by abcdw** [magnars/dash.el#382]
Hi, can you release 2.19, please?

I would like to update package for dash.el in Guix repository to make it possible to build it with emacs28.

Thanks a lot for all your work!)

**Comment by basil-conto** [comment]
Thanks for the nudge! As far as I'm concerned, the only blocker in https://github.com/magnars/dash.el/projects/2 is wrapping up the indentation changes and features discussed in #375 (I'd rather not cut a release with indentation changes that users disagree with).  If I have time I'd also like to clean up #308.

I'm hoping to be able to finish these by next week, if that's okay.

**Comment by abcdw** [comment]
"Basil L. Contovounesios" ***@***.***> writes:

> Thanks for the nudge! As far as I'm concerned, the only blocker in
> https://github.com/magnars/dash.el/projects/2 is wrapping up the
> indentation changes and features discussed in #375 (I'd rather not cut
> a release with indentation changes that users disagree with).  If I
> have time I'd also like to clean up #308.
>
> I'm hoping to be able to finish these by next week, if that's okay.

Cool, thank you very much!)

**Comment by magnars** [comment]
Excellent. Thank you for getting this together, @basil-conto 😄

**Comment by abcdw** [comment]
"Basil L. Contovounesios" ***@***.***> writes:

> Closed #382 via 2675596b9ac1c4b9d47b93e227f06f8ec6755ec6.

Thanks a lot!)  Seems working with Emacs 28.

Sent a patch for GNU Guix package manager: https://issues.guix.gnu.org/49488

**Comment by basil-conto** [comment]
You're welcome, and thanks for confirming and working on this!
