### ISSUE TITLE
`-permutations` doesn't work correctly with lists with duplications.

### ISSUE THREAD

**Issue by evjava** [magnars/dash.el#390]
Example:
`(-permutations (list 1 1 2))`

Expected: `((1 1 2) (1 2 1) (2 1 1))`
Actual: `((1 2) (1 2) (2 1) (2 1))`

Version: 2.19.1

**Comment by basil-conto** [comment]
Thanks for reporting this!  Patches to fix this are most welcome (unfortunately I'll be AFK for extended periods of time over the coming months, so I can't promise to look into it myself).

**Comment by ComedyTomedy** [comment]
Not nice, but seems to work.

    (defun -permutations (list)
      "Return the permutations of LIST."
      (if (null list) '(())
        (-uniq (mapcan (lambda (x)
        		     (mapcar (lambda (perm) (cons x perm))
        			     (-permutations (-remove-first (-partial #'equal x) list))))
        		   list))))

**Comment by Fuco1** [comment]
TBH I would almost prefer to error out on duplicate inputs and provide a different function for permutations with repetition.  It gets tricky very fast.

**Comment by Fuco1** [comment]
@ComedyTomedy Your code returns `((1 1 2) (1 2 1) (2 1))` on the test input `(1 1 2)`

**Comment by Fuco1** [comment]
Here's an implementation without `-uniq` which can really make the algorithm SUPER slow.  Try the input `(list 1 1 1 1 1 1 1 1 1)` which will compute 362880 results only to throw away 362879 of them.

The following implementation first makes a list of counts of each unique item and then uses the original algorithm recursively removing items from the pool.  For the OP example, `(list 1 1 2)` becomes `((1 . 2) (2 . 1))` (one two and two ones).  This new structure is then passed to `dash--perms` internal function.

```elisp
(defun -perms (list)
  (dash--perms
   (--map (cons (car it) (length (cdr it)))
          (-group-by 'identity list))))

(defun dash--perms (list)
  (if (null list) '(())
    (-mapcat
     (-lambda ((elem . count))
       (mapcar (lambda (perm) (cons elem perm))
               (if (> count 1)
                   (dash--perms (cons (cons elem (1- count))
                                      (--remove (equal (car it) elem) list)))
                 (dash--perms (--remove (equal (car it) elem) list)))))
     list)))
```

**Comment by ComedyTomedy** [comment]
I did suspect that uniq might be a bad choice :)

Clojure's combinatorics/permutations switches algorithm depending on the input:

    (cond
      (sorted-numbers? items) ...
      (all-different? items) ...
      :else ...)

**Comment by Fuco1** [comment]
I think it's more consistent to not return duplicate permutations.  I don't immediately see how that could be of use.

**Comment by basil-conto** [comment]
How does the implementation in #399 look to ye?
