### ISSUE TITLE
(-unzip (-zip ...)) isn't identity, and I'm not sure it can ever be

### ISSUE THREAD

**Issue by hraban** [magnars/dash.el#400]
The documentation for `-unzip` states that it is the inverse of `-zip`:

> Unzip LISTS.
>
> This works just like `-zip` but takes a list of lists instead of
> a variable number of arguments, such that
>
>     (-unzip (-zip L1 L2 L3 ...))
>
> is identity (given that the lists are the same length).
>
> Note in particular that calling this on a list of two lists will
> return a list of cons-cells such that the above identity works.
>
> See also: `-zip`

But it doesn't work out that way:

      (-unzip (-zip '(1 2 3) '(4 5 6)))

is an error.

And I'm not sure it ever could be, because `-zip` is not injective because of the weird consing of pairs, so there is no inverse possible. E.g.:

    (-zip '(1 4 7) '((2 3) (5 6) (8 9)))
    => ((1 2 3) (4 5 6) (7 8 9))

    (-zip '(1 4 7) '(2 5 8) '(3 6 9))
    => ((1 2 3) (4 5 6) (7 8 9))

(Though technically even a "clean" zip like `-zip-lists` is not injective because `(zip ())` = `(zip () ())` = `(zip () () ())` ...)

I'm guessing this needs an update to the docs, and optionally a new function "-unzip-lists" or similar, which can be more reliably used as a (quasi-)inverse.

What do you think?

**Comment by basil-conto** [comment]
Some context from [`README.md`](https://github.com/magnars/dash.el/blob/master/README.md#upcoming-breaking-change) (emphasis mine):

> ### Upcoming breaking change!
> 
> - For backward compatibility reasons, `-zip` **when called with two
>   lists** returns a list of cons cells, rather than a list of proper
>   lists.  This is a clunky API, and may be changed in a future release
>   to always return a list of proper lists, as `-zip-lists` currently
>   does.
> 
>   **N.B.: Do not rely on the current behavior of `-zip` for two
>   lists.**  Instead, use `-zip-pair` for a list of cons cells, and
>   `-zip-lists` for a list of proper lists.

Indeed, the example in the docstring of `-unzip` is careful to pass more than two lists as arguments to `-zip`:

> This works just like `-zip` but takes a list of lists instead of
> a variable number of arguments, such that
> ```el
> (-unzip (-zip L1 L2 L3 ...))
> ```
> is identity (given that the lists are the same length).

---

> I'm guessing this needs an update to the docs

What would you suggest changing?

> a new function "-unzip-lists" or similar

What would this function do, call `-zip-lists` instead of `-zip`?

Thanks!

**Comment by hraban** [comment]
Ah, great news about `-zip` being updated to look more like `-zip-lists`.

In that case, everything will solve itself automatically.

I was under the impression that "L1 L2 L3..." meant "L*", including just "L1 L2" :) but that is moot if `-zip` will become `-zip-lists`, and `-unzip` with it.

If anything is even necessary at this point, the best thing I can come up with is adding that disclaimer to the docstring of those two functions. To help people like me, who don't stay abreast of updates in the project's README when using the code :)

Thanks 👍

**Comment by hraban** [comment]
Agreed with the `-unzip-lists`. And I don't think this part of the docstring of `-unzip` is accurate:

> Note in particular that calling ‘-unzip’ on a list of two lists
will return a list of cons cells _such that the above identity
works._

It doesn't make the identity work. `-zip` and `-unzip` are not inverses. I'd remove any mention of inverse, or identity, from the `-unzip` docstring entirely, and move it to `-unzip-lists` instead.

```
(-zip '(a b c) '(d e f))
=> ((a . d) (b . e) (c . f))
(-unzip '((a b c) (d e f)))
=> ((a . d) (b . e) (c . f))
(-unzip '((a . d) (b . e) (c . f)))
=> Lisp error: (wrong-type-argument listp d)
```

-zip and -unzip are not inverses, and the consing behaviour of -unzip does not help making it an inverse. Calling -unzip on the output of -zip with two lists is an error.

**Comment by basil-conto** [comment]
> > To be honest, for backward compatibility reasons this is not something I personally intend to see through. Perhaps another maintainer will.
> 
> We could make a note of it in the docstring perhaps, but yeah, let's avoid breaking changes. :+1:

Should the prominent caveat in [`README.md`](https://github.com/magnars/dash.el/blob/master/README.md#upcoming-breaking-change) remain?  It vaguely promises "may be changed in the future", which is accurate, but if no-one actually intends to do this, maybe we should just move any relevant info to the docstring of `-zip`?

**Comment by magnars** [comment]
I'm inclined to err on the side of stability, so that sounds good to me.

**Comment by basil-conto** [comment]
Sorry for the long delay in finishing this up.

Please have a look at the new functions and docs and let me know if there's any room for improvement or anything amiss. Thanks.

**Comment by tarsius** [comment]
:fireworks: :grin: 

For more background: #135.

**Comment by basil-conto** [comment]
> For more background: #135.

Ah thanks, I forgot to look at and link to past discussions this time! :sweat_smile:
