### ISSUE TITLE
Trouble with --map-when?

### ISSUE THREAD

**Issue by smandy** [magnars/dash.el#416]
AFAIT these two expressions should return same result.

```
(--map-when #'evenp (* it it) (number-sequence 1 10))
(--map (if (evenp it) (* it it) it) (number-sequence 1 10))
```

but I get ....

```
(--map-when #'evenp (* it it) (number-sequence 1 10)) (1 4 9 16 25 36 49 64 81 100)
(--map (if (evenp it) (* it it) it) (number-sequence 1 10))(1 4 3 16 5 36 7 64 9 100)
```

I don't understand?!

**Comment by basil-conto** [comment]
`--map-when` evaluates its first argument for each element `it` of the list, and `#'evenp` unconditionally evaluates to a non-`nil` value irrespective of `it`.

Have you tried `(--map-when (evenp it) ...)` instead?

**Comment by smandy** [comment]
Makes sense - thanks for the answer. Sorry for late reply.

**Comment by smandy** [comment]
Yeah think I understand this now .....
