### ISSUE TITLE
Make dash a sequence API instead of a list API

### ISSUE THREAD

**Issue by bbatsov** [magnars/dash.el#43]
While lists are the most popular portion of Emacs Lisp's sequential API we still have to consider other sequential structures like vectors and strings. Without support for them dash cannot replace the sequential API provided by `cl-lib` in all possible scenarios and that's a shame, since dash's API is so much better.

We've discussed this already at Twitter and I know that at least a few people like @lunaryorn and @joelmccracken support my suggestion.  Ideally when operating on a string/vector the functions would return a string or vector, but even a list would do (I assume this would be much easier to implement).

**Comment by CestDiego** [comment]
any progress here? this is so needed by me now that I can't use `--group-by` on vectors that are returned when I do  a `json-read` from a json received after an http-request :( so changing it to lists is not really convenient

**Comment by bbatsov** [comment]
I've now moved to `seq.el`, so I no longer care about this.
