### ISSUE TITLE
[discussion] Lazy streams?

### ISSUE THREAD

**Issue by shosti** [magnars/dash.el#80]
I've recently been playing around with implementing lazy streams in Elisp (https://github.com/shosti/smash.el), and it occurred to me that it might be possible to integrate laziness into dash.el instead of re-implementing lazy versions of everything. Is that something you'd be interested in pursuing? (I'm not yet sure of their performance or general usefulness for Emacs programming, but they allow for some neat things).  

I think it might even be possible without breaking backwards-compatibility or requiring Emacs 24. Basically, you'd need a macro that would create two versions of each function, one that outputs a stream and one that outputs a list (maybe postfix lazy versions with a symbol, i.e. -take$ or something). The lazy version would only be generated in Emacs 24. In the macro, you'd also coerce the input to a list or stream (for the eager and lazy versions, respectively). smash.el already handles inputs that are either streams or lists, through some basic type-tagging. 

This would probably be at odds with the approach described in https://github.com/magnars/dash.el/issues/43, but it would have the advantage of being extensible to user-defined data structures--you'd just need a mechanism to "install" a coercion function for the data structure (similar to the `seq` abstraction in Clojure). Personally, I'm a fan of Clojure's "anything goes in, but `seq`s come out" approach to generic list functions, and I think guessing the desired output type without a static type system is kind of problematic. But I could also see laziness being outside the scope of dash.el (I don't really have any real need for lazy streams, and was just implementing them for fun). Let me know what you think.

**Comment by basil-conto** [comment]
Nowadays Emacs core has `seq.el` which is implemented in terms of extensible generic functions [`(info "(elisp) Sequence Functions")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Sequence-Functions.html#index-seq-library), and GNU ELPA provides the `stream` package with lazy streams built on top of it (https://elpa.gnu.org/packages/stream.html).

Given the lack of interest in this issue in the last 6+ years, I'm now closing this issue, but we can always reopen it if needed.
