### ISSUE TITLE
alias -butlast to butlast

### ISSUE THREAD

**Issue by Fuco1** [magnars/dash.el#99]
There's `butlast` built-in fuction, which uses subroutines implemented in C, so it should be quite a lot faster.  Is there any reason this wasn't used? (other than maybe you didn't know about it?)

**Comment by Fuco1** [comment]
@rejeep I take it `-take-last` would take `n` last items. Maybe we could support negative arguments to `-take` and `-drop` to mean "go from the end", as is the tradition in python and similar languages.

`-take -1 list` would then be equal to `butlast list`.  I also don't like the fact that butlast would take optional numeric argument as second argument, making the API inconsistent.

So `-butlast` should just really return the list without the last element, taking no extra arguments.  `-take` or `-take-last` should have the call syntax `n list` and and return the sublist.

**Comment by rejeep** [comment]
@Fuco1 Both would work, but I think the API is easier to understand with `*-last`, than with negative argument.

**Comment by magnars** [comment]
While negative arguments are a staple of Emacs Lisp, I agree with Johan.
`(forward-char -1)` never sat right with me.

**Comment by Fuco1** [comment]
There are certain cases where negative arguments are handy, for example when you compute the index and then pass it into a function... you don't need to have an if and special case positive or negative offset (with `forward-char` that is).  I agree that such a situation would likely not occur with `-take`, especially if the semantics are not offset but "start from the end".

I'm OK with having two functions as well.

**Comment by magnars** [comment]
Good point.

**Comment by Fuco1** [comment]
I decided against adding the negative arguments, because while with `forward-char` it makes sense as the offset operates from the point in both cases, the `-1` to `-take` operates from the end and so it is not relative to the beginning, making it very hard to "compute the offset dynamically" as it is radically different from the positive value.

Thanks for the input y'all.
